//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUDataStatInfo;
@class KPUServiceInfo;
@class KPUAssetUpdateInfo;
@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUAssetInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getDataStat) KPUDataStatInfo* DataStat;

@property (retain,nonatomic,getter=getService) KPUServiceInfo* Service;

@property (retain,nonatomic,getter=getUpdateAsset) KPUAssetUpdateInfo* UpdateAsset;

@property (retain,nonatomic,getter=get_SellPrice) NSNumber* _SellPrice;

@property (retain,nonatomic,getter=getCurrencySymbol) NSString* CurrencySymbol;

@property (retain,nonatomic,getter=getRatio) NSNumber* Ratio;

@property (retain,nonatomic,getter=getPKAssetId) NSNumber* PKAssetId;

@property (retain,nonatomic,getter=getFKAssetCategoryId) NSNumber* FKAssetCategoryId;

@property (retain,nonatomic,getter=getFKOwnerId) NSNumber* FKOwnerId;

@property (retain,nonatomic,getter=getFKBrandId) NSNumber* FKBrandId;

@property (retain,nonatomic,getter=getFKModelId) NSNumber* FKModelId;

@property (retain,nonatomic,getter=getAssetName) NSString* AssetName;

@property (retain,nonatomic,getter=getAssetLocation) NSString* AssetLocation;

@property (retain,nonatomic,getter=getComment) NSString* Comment;

@property (nonatomic,getter=getIsActive) BOOL IsActive;

@property (retain,nonatomic,getter=getDateCreated) NSDate* DateCreated;

@property (nonatomic,getter=getOverRule) BOOL OverRule;

@property (nonatomic,getter=getFKRecordStatId) int FKRecordStatId;

@property (retain,nonatomic,getter=getRealname) NSString* Realname;

@property (nonatomic,getter=getFKCustomerId) int FKCustomerId;

@property (retain,nonatomic,getter=getBRealName) NSString* BRealName;

@property (retain,nonatomic,getter=getAssetCategoryName) NSString* AssetCategoryName;

@property (retain,nonatomic,getter=getUpdateUser) NSString* UpdateUser;

@property (retain,nonatomic,getter=getCreateUser) NSString* CreateUser;

@property (retain,nonatomic,getter=getCreatedDateTime) NSDate* CreatedDateTime;

@property (retain,nonatomic,getter=getUpdatedDateTime) NSDate* UpdatedDateTime;

@property (retain,nonatomic,getter=getBrandName) NSString* BrandName;

@property (retain,nonatomic,getter=getStandardWorkRequestName) NSString* StandardWorkRequestName;

@property (retain,nonatomic,getter=getModelName) NSString* ModelName;

@property (retain,nonatomic,getter=getAssetBlog) NSString* AssetBlog;

@property (retain,nonatomic,getter=getAssetCategoryFieldName) NSString* AssetCategoryFieldName;

@property (retain,nonatomic,getter=getFieldValue) NSString* FieldValue;

@property (retain,nonatomic,getter=getUserName) NSString* UserName;

@property (nonatomic,getter=getAssetType) int AssetType;

@property (nonatomic,getter=getWebsiteVisible) BOOL WebsiteVisible;

@property (retain,nonatomic,getter=getMarketing) NSString* Marketing;

@property (retain,nonatomic,getter=getManufacturer) NSString* Manufacturer;

@property (retain,nonatomic,getter=getModelNumber) NSString* ModelNumber;

@property (retain,nonatomic,getter=getTechnicalInfo) NSString* TechnicalInfo;

@property (retain,nonatomic,getter=getMoreInfoLink) NSString* MoreInfoLink;

@property (retain,nonatomic,getter=getReference) NSString* Reference;

@property (retain,nonatomic,getter=getBuyPrice) NSNumber* BuyPrice;

@property (retain,nonatomic,getter=getBuycurrencySymbol) NSString* BuycurrencySymbol;

@property (retain,nonatomic,getter=getBuycurrencyCode) NSString* BuycurrencyCode;

@property (retain,nonatomic,getter=getSellPrice) NSNumber* SellPrice;

@property (retain,nonatomic,getter=getSellCurrencySymbol) NSString* SellCurrencySymbol;

@property (retain,nonatomic,getter=getSellcurrencyCode) NSString* SellcurrencyCode;

@property (retain,nonatomic,getter=getWebPageTitle) NSString* WebPageTitle;

@property (retain,nonatomic,getter=getWebPageDesc) NSString* WebPageDesc;

@property (retain,nonatomic,getter=getShippingTime) NSNumber* ShippingTime;

@property (retain,nonatomic,getter=getAssetImage) NSString* AssetImage;

@property (retain,nonatomic,getter=getAssetThumbnail) NSString* AssetThumbnail;

@property (retain,nonatomic,getter=getFKRelatedId) NSNumber* FKRelatedId;

@property (retain,nonatomic,getter=getInStock) NSNumber* InStock;

@property (retain,nonatomic,getter=getFKStandardWorkRequestId) NSNumber* FKStandardWorkRequestId;

@property (retain,nonatomic,getter=getFKBuyCurrencyId) NSNumber* FKBuyCurrencyId;

@property (retain,nonatomic,getter=getFKSellCurrencyId) NSNumber* FKSellCurrencyId;

@property (retain,nonatomic,getter=getIndexNumber) NSNumber* IndexNumber;

@property (nonatomic,getter=getIsAllCustomers) BOOL IsAllCustomers;

@property (nonatomic,getter=getDefaultCurrency) int DefaultCurrency;

@property (retain,nonatomic,getter=getSellingSiteName) NSString* SellingSiteName;

@property (retain,nonatomic,getter=getSoftwareInventory) NSString* SoftwareInventory;

@property (nonatomic,getter=getPoints) int Points;

@property (nonatomic,getter=getBonusPoints) int BonusPoints;

@property (nonatomic,getter=getPSATerm) int PSATerm;

@property (nonatomic,getter=getEngineerVisible) BOOL EngineerVisible;

@property (retain,nonatomic,getter=getConsumerType) NSNumber* ConsumerType;

@property (retain,nonatomic,getter=getResponseUnitName) NSString* ResponseUnitName;

@property (retain,nonatomic,getter=getResolutionUnitname) NSString* ResolutionUnitname;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUAssetInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end