//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUBindServiceByDeptDSResponse_BindServiceByDeptDSResult : NSObject <KPUISerializableObject>

-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUBindServiceByDeptDSResponse_BindServiceByDeptDSResult*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end