//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUCredentialInfo.h"
#import "KPUDataStatInfo.h"
#import "KPUCustomerUpdateInfo.h"
#import "KPUEmailDomainInfo.h"
#import "KPUHelper.h"
#import "KPUCustomerInfo.h"


@implementation KPUCustomerInfo
@synthesize Credential;
@synthesize DataStats;
@synthesize MakeAssistantToId;
@synthesize UpdateCustomer;
@synthesize objEmailDomain;
@synthesize FKPaymentStatusId;
@synthesize PKCustomerID;
@synthesize FKCustomerID;
@synthesize TotalLogins;
@synthesize FKRecordStatID;
@synthesize FKCredentialID;
@synthesize Business;
@synthesize FirstName;
@synthesize MiddleName;
@synthesize LastName;
@synthesize CreateTicket;
@synthesize UpdateTicket;
@synthesize Closeticket;
@synthesize IsCoordinator;
@synthesize LastIPAddress;
@synthesize VATNumber;
@synthesize LastWANIP;
@synthesize Overrule;
@synthesize Industry;
@synthesize CompanySize;
@synthesize CreatedDatetime;
@synthesize LastLoginTIme;
@synthesize UserName;
@synthesize ISActive;
@synthesize RealName;
@synthesize Location;
@synthesize IndividualCount;
@synthesize AssetCount;
@synthesize HasAsset;
@synthesize hasEmployee;
@synthesize CreateUser;
@synthesize UpdateUser;
@synthesize UpdatedDateTime;
@synthesize SupportLanguage;
@synthesize SecurityRoleName;
@synthesize ResponseSLA;
@synthesize ResolutionSLA;
@synthesize TeamViewerId;
@synthesize DefaultCurrencySymbol;
@synthesize CurrencySymbol;
@synthesize CurrencyCode;
@synthesize EmailAddress;
@synthesize IsMobile;
@synthesize IsQualified;
@synthesize HitCount;
@synthesize ContactType;
@synthesize CustomerName;
@synthesize EmployeeName;
@synthesize LastContactDate;
@synthesize TicketCount;
@synthesize FKResellerID;
@synthesize CustPhoneNumber;
@synthesize FKDefaultAssetID;
@synthesize PayAsYouGoValidity;
@synthesize PayAsYouGoBalance;
@synthesize SubscriptionValidity;
@synthesize SubscriptionBalance;
@synthesize IsCreditApproved;
@synthesize CreditAmount;
@synthesize LanguageName;
@synthesize PointsAvailable;
@synthesize LastUsed;
@synthesize CanBuyServices;
@synthesize CreditBalance;
@synthesize AgentExchangeRate;
@synthesize AccountName;
@synthesize PhoneNumber;
@synthesize DefaultAssetName;
@synthesize PointsPurchased;
@synthesize TotalPointsSpent;
@synthesize MonthlyPointsSpent;
@synthesize YearlyPointsSpent;
@synthesize PSATerm;
@synthesize CreditExpire;
@synthesize PaymentTerms;
@synthesize FKSecurityRoleId;
@synthesize FKMenuId;
@synthesize EmailForFreePoints;
@synthesize FKReferrerID;
@synthesize FKEngineerID;
@synthesize ResellerSupportEmail;
@synthesize ResellerHasWebsite;
@synthesize ResellerWebsiteURL;
@synthesize PreferredExpertID;
@synthesize PreferredExpertName;
@synthesize ReferrerName;
@synthesize ReferredByID;
@synthesize ReferredByUserType;
@synthesize DefaultServicePoints;
@synthesize FriendPoints;
@synthesize Pointsawarded;
@synthesize CustomerResellerType;
@synthesize CountryCodeInfo;
@synthesize CountryCode;
@synthesize CompanyRegNo;
@synthesize FkSellingSiteID;
@synthesize CountryName;
@synthesize KnownVia;
@synthesize Functions;
@synthesize CompanyName;
@synthesize Website;
@synthesize PointsMultiplier;
@synthesize CSymbol;
@synthesize FKResellerEmployeeID;
@synthesize SpendAvailable;

+ (KPUCustomerInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.MakeAssistantToId =0;
        self.FKPaymentStatusId =[NSNumber numberWithInt:0];
        self.PKCustomerID =[NSNumber numberWithInt:0];
        self.FKCustomerID =[NSNumber numberWithInt:0];
        self.TotalLogins =0;
        self.FKRecordStatID =[NSNumber numberWithInt:0];
        self.FKCredentialID =[NSNumber numberWithInt:0];
        self.IndividualCount =0;
        self.AssetCount =0;
        self.HasAsset =0;
        self.hasEmployee =0;
        self.ResponseSLA =0;
        self.ResolutionSLA =0;
        self.HitCount =0;
        self.TicketCount =0;
        self.FKResellerID =[NSNumber numberWithInt:0];
        self.FKDefaultAssetID =[NSNumber numberWithInt:0];
        self.PayAsYouGoBalance =[NSNumber numberWithInt:0];
        self.SubscriptionBalance =[NSNumber numberWithInt:0];
        self.CreditAmount =[NSNumber numberWithInt:0];
        self.CreditBalance =[NSNumber numberWithInt:0];
        self.AgentExchangeRate =[NSNumber numberWithInt:0];
        self.PointsPurchased =0;
        self.TotalPointsSpent =0;
        self.MonthlyPointsSpent =0;
        self.YearlyPointsSpent =0;
        self.PSATerm =0;
        self.PaymentTerms =[NSNumber numberWithInt:0];
        self.FKSecurityRoleId =[NSNumber numberWithInt:0];
        self.FKMenuId =0;
        self.FKReferrerID =0;
        self.FKEngineerID =0;
        self.PreferredExpertID =0;
        self.ReferredByID =0;
        self.ReferredByUserType =0;
        self.DefaultServicePoints =0;
        self.FriendPoints =0;
        self.CustomerResellerType =[NSNumber numberWithInt:0];
        self.FkSellingSiteID =0;
        self.PointsMultiplier =[NSNumber numberWithInt:0];
        self.FKResellerEmployeeID =[NSNumber numberWithInt:0];
        self.SpendAvailable =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"Credential" index:0])
        {
            self.Credential = (KPUCredentialInfo*)[__request createObject:[KPUHelper getNode:__node name:@"Credential" index:0] type:[KPUCredentialInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"DataStats" index:0])
        {
            self.DataStats = (KPUDataStatInfo*)[__request createObject:[KPUHelper getNode:__node name:@"DataStats" index:0] type:[KPUDataStatInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"MakeAssistantToId" index:0])
        {
            self.MakeAssistantToId = [[[KPUHelper getNode:__node name:@"MakeAssistantToId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdateCustomer" index:0])
        {
            self.UpdateCustomer = (KPUCustomerUpdateInfo*)[__request createObject:[KPUHelper getNode:__node name:@"UpdateCustomer" index:0] type:[KPUCustomerUpdateInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"objEmailDomain" index:0])
        {
            self.objEmailDomain = (KPUEmailDomainInfo*)[__request createObject:[KPUHelper getNode:__node name:@"objEmailDomain" index:0] type:[KPUEmailDomainInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"FKPaymentStatusId" index:0])
        {
            self.FKPaymentStatusId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKPaymentStatusId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PKCustomerID" index:0])
        {
            self.PKCustomerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKCustomerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKCustomerID" index:0])
        {
            self.FKCustomerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKCustomerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"TotalLogins" index:0])
        {
            self.TotalLogins = [[[KPUHelper getNode:__node name:@"TotalLogins" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FKRecordStatID" index:0])
        {
            self.FKRecordStatID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKRecordStatID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKCredentialID" index:0])
        {
            self.FKCredentialID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKCredentialID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Business" index:0])
        {
            self.Business = [[[KPUHelper getNode:__node name:@"Business" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"FirstName" index:0])
        {
            self.FirstName = [[KPUHelper getNode:__node name:@"FirstName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"MiddleName" index:0])
        {
            self.MiddleName = [[KPUHelper getNode:__node name:@"MiddleName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastName" index:0])
        {
            self.LastName = [[KPUHelper getNode:__node name:@"LastName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CreateTicket" index:0])
        {
            self.CreateTicket = [[[KPUHelper getNode:__node name:@"CreateTicket" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdateTicket" index:0])
        {
            self.UpdateTicket = [[[KPUHelper getNode:__node name:@"UpdateTicket" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"Closeticket" index:0])
        {
            self.Closeticket = [[[KPUHelper getNode:__node name:@"Closeticket" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"IsCoordinator" index:0])
        {
            self.IsCoordinator = [[[KPUHelper getNode:__node name:@"IsCoordinator" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"LastIPAddress" index:0])
        {
            self.LastIPAddress = [[KPUHelper getNode:__node name:@"LastIPAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"VATNumber" index:0])
        {
            self.VATNumber = [[KPUHelper getNode:__node name:@"VATNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastWANIP" index:0])
        {
            self.LastWANIP = [[KPUHelper getNode:__node name:@"LastWANIP" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Overrule" index:0])
        {
            self.Overrule = [[[KPUHelper getNode:__node name:@"Overrule" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"Industry" index:0])
        {
            self.Industry = [[KPUHelper getNode:__node name:@"Industry" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CompanySize" index:0])
        {
            self.CompanySize = [[KPUHelper getNode:__node name:@"CompanySize" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CreatedDatetime" index:0])
        {
            self.CreatedDatetime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"CreatedDatetime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"LastLoginTIme" index:0])
        {
            self.LastLoginTIme = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastLoginTIme" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UserName" index:0])
        {
            self.UserName = [[KPUHelper getNode:__node name:@"UserName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ISActive" index:0])
        {
            self.ISActive = [[[KPUHelper getNode:__node name:@"ISActive" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"RealName" index:0])
        {
            self.RealName = [[KPUHelper getNode:__node name:@"RealName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Location" index:0])
        {
            self.Location = [[KPUHelper getNode:__node name:@"Location" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IndividualCount" index:0])
        {
            self.IndividualCount = [[[KPUHelper getNode:__node name:@"IndividualCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AssetCount" index:0])
        {
            self.AssetCount = [[[KPUHelper getNode:__node name:@"AssetCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"HasAsset" index:0])
        {
            self.HasAsset = [[[KPUHelper getNode:__node name:@"HasAsset" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"hasEmployee" index:0])
        {
            self.hasEmployee = [[[KPUHelper getNode:__node name:@"hasEmployee" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"CreateUser" index:0])
        {
            self.CreateUser = [[KPUHelper getNode:__node name:@"CreateUser" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdateUser" index:0])
        {
            self.UpdateUser = [[KPUHelper getNode:__node name:@"UpdateUser" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedDateTime" index:0])
        {
            self.UpdatedDateTime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"UpdatedDateTime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SupportLanguage" index:0])
        {
            self.SupportLanguage = [[KPUHelper getNode:__node name:@"SupportLanguage" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"SecurityRoleName" index:0])
        {
            self.SecurityRoleName = [[KPUHelper getNode:__node name:@"SecurityRoleName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ResponseSLA" index:0])
        {
            self.ResponseSLA = [[[KPUHelper getNode:__node name:@"ResponseSLA" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ResolutionSLA" index:0])
        {
            self.ResolutionSLA = [[[KPUHelper getNode:__node name:@"ResolutionSLA" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"TeamViewerId" index:0])
        {
            self.TeamViewerId = [[KPUHelper getNode:__node name:@"TeamViewerId" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"DefaultCurrencySymbol" index:0])
        {
            self.DefaultCurrencySymbol = [[KPUHelper getNode:__node name:@"DefaultCurrencySymbol" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CurrencySymbol" index:0])
        {
            self.CurrencySymbol = [[KPUHelper getNode:__node name:@"CurrencySymbol" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CurrencyCode" index:0])
        {
            self.CurrencyCode = [[KPUHelper getNode:__node name:@"CurrencyCode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"EmailAddress" index:0])
        {
            self.EmailAddress = [[KPUHelper getNode:__node name:@"EmailAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsMobile" index:0])
        {
            self.IsMobile = [[[KPUHelper getNode:__node name:@"IsMobile" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"IsQualified" index:0])
        {
            self.IsQualified = [[[KPUHelper getNode:__node name:@"IsQualified" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"HitCount" index:0])
        {
            self.HitCount = [[[KPUHelper getNode:__node name:@"HitCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ContactType" index:0])
        {
            self.ContactType = [[KPUHelper getNode:__node name:@"ContactType" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CustomerName" index:0])
        {
            self.CustomerName = [[KPUHelper getNode:__node name:@"CustomerName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"EmployeeName" index:0])
        {
            self.EmployeeName = [[KPUHelper getNode:__node name:@"EmployeeName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastContactDate" index:0])
        {
            self.LastContactDate = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastContactDate" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"TicketCount" index:0])
        {
            self.TicketCount = [[[KPUHelper getNode:__node name:@"TicketCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FKResellerID" index:0])
        {
            self.FKResellerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKResellerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CustPhoneNumber" index:0])
        {
            self.CustPhoneNumber = [[KPUHelper getNode:__node name:@"CustPhoneNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKDefaultAssetID" index:0])
        {
            self.FKDefaultAssetID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKDefaultAssetID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PayAsYouGoValidity" index:0])
        {
            self.PayAsYouGoValidity = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"PayAsYouGoValidity" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PayAsYouGoBalance" index:0])
        {
            self.PayAsYouGoBalance = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PayAsYouGoBalance" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SubscriptionValidity" index:0])
        {
            self.SubscriptionValidity = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"SubscriptionValidity" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SubscriptionBalance" index:0])
        {
            self.SubscriptionBalance = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"SubscriptionBalance" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"IsCreditApproved" index:0])
        {
            self.IsCreditApproved = [[[KPUHelper getNode:__node name:@"IsCreditApproved" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CreditAmount" index:0])
        {
            self.CreditAmount = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CreditAmount" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"LanguageName" index:0])
        {
            self.LanguageName = [[KPUHelper getNode:__node name:@"LanguageName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PointsAvailable" index:0])
        {
            self.PointsAvailable = [[KPUHelper getNode:__node name:@"PointsAvailable" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastUsed" index:0])
        {
            self.LastUsed = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastUsed" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CanBuyServices" index:0])
        {
            self.CanBuyServices = [[[KPUHelper getNode:__node name:@"CanBuyServices" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CreditBalance" index:0])
        {
            self.CreditBalance = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CreditBalance" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"AgentExchangeRate" index:0])
        {
            self.AgentExchangeRate = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"AgentExchangeRate" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"AccountName" index:0])
        {
            self.AccountName = [[KPUHelper getNode:__node name:@"AccountName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PhoneNumber" index:0])
        {
            self.PhoneNumber = [[KPUHelper getNode:__node name:@"PhoneNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"DefaultAssetName" index:0])
        {
            self.DefaultAssetName = [[KPUHelper getNode:__node name:@"DefaultAssetName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PointsPurchased" index:0])
        {
            self.PointsPurchased = [[[KPUHelper getNode:__node name:@"PointsPurchased" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"TotalPointsSpent" index:0])
        {
            self.TotalPointsSpent = [[[KPUHelper getNode:__node name:@"TotalPointsSpent" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"MonthlyPointsSpent" index:0])
        {
            self.MonthlyPointsSpent = [[[KPUHelper getNode:__node name:@"MonthlyPointsSpent" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"YearlyPointsSpent" index:0])
        {
            self.YearlyPointsSpent = [[[KPUHelper getNode:__node name:@"YearlyPointsSpent" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"PSATerm" index:0])
        {
            self.PSATerm = [[[KPUHelper getNode:__node name:@"PSATerm" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"CreditExpire" index:0])
        {
            self.CreditExpire = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"CreditExpire" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PaymentTerms" index:0])
        {
            self.PaymentTerms = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PaymentTerms" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKSecurityRoleId" index:0])
        {
            self.FKSecurityRoleId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKSecurityRoleId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKMenuId" index:0])
        {
            self.FKMenuId = [[[KPUHelper getNode:__node name:@"FKMenuId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"EmailForFreePoints" index:0])
        {
            self.EmailForFreePoints = [[[KPUHelper getNode:__node name:@"EmailForFreePoints" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"FKReferrerID" index:0])
        {
            self.FKReferrerID = [[[KPUHelper getNode:__node name:@"FKReferrerID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FKEngineerID" index:0])
        {
            self.FKEngineerID = [[[KPUHelper getNode:__node name:@"FKEngineerID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ResellerSupportEmail" index:0])
        {
            self.ResellerSupportEmail = [[KPUHelper getNode:__node name:@"ResellerSupportEmail" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ResellerHasWebsite" index:0])
        {
            self.ResellerHasWebsite = [[[KPUHelper getNode:__node name:@"ResellerHasWebsite" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"ResellerWebsiteURL" index:0])
        {
            self.ResellerWebsiteURL = [[KPUHelper getNode:__node name:@"ResellerWebsiteURL" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PreferredExpertID" index:0])
        {
            self.PreferredExpertID = [[[KPUHelper getNode:__node name:@"PreferredExpertID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"PreferredExpertName" index:0])
        {
            self.PreferredExpertName = [[KPUHelper getNode:__node name:@"PreferredExpertName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferrerName" index:0])
        {
            self.ReferrerName = [[KPUHelper getNode:__node name:@"ReferrerName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferredByID" index:0])
        {
            self.ReferredByID = [[[KPUHelper getNode:__node name:@"ReferredByID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferredByUserType" index:0])
        {
            self.ReferredByUserType = [[[KPUHelper getNode:__node name:@"ReferredByUserType" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"DefaultServicePoints" index:0])
        {
            self.DefaultServicePoints = [[[KPUHelper getNode:__node name:@"DefaultServicePoints" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FriendPoints" index:0])
        {
            self.FriendPoints = [[[KPUHelper getNode:__node name:@"FriendPoints" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"Pointsawarded" index:0])
        {
            self.Pointsawarded = [[[KPUHelper getNode:__node name:@"Pointsawarded" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CustomerResellerType" index:0])
        {
            self.CustomerResellerType = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CustomerResellerType" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CountryCodeInfo" index:0])
        {
            self.CountryCodeInfo = [[KPUHelper getNode:__node name:@"CountryCodeInfo" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CountryCode" index:0])
        {
            self.CountryCode = [[KPUHelper getNode:__node name:@"CountryCode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CompanyRegNo" index:0])
        {
            self.CompanyRegNo = [[KPUHelper getNode:__node name:@"CompanyRegNo" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FkSellingSiteID" index:0])
        {
            self.FkSellingSiteID = [[[KPUHelper getNode:__node name:@"FkSellingSiteID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"CountryName" index:0])
        {
            self.CountryName = [[KPUHelper getNode:__node name:@"CountryName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"KnownVia" index:0])
        {
            self.KnownVia = [[KPUHelper getNode:__node name:@"KnownVia" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Functions" index:0])
        {
            self.Functions = [[KPUHelper getNode:__node name:@"Functions" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CompanyName" index:0])
        {
            self.CompanyName = [[KPUHelper getNode:__node name:@"CompanyName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Website" index:0])
        {
            self.Website = [[KPUHelper getNode:__node name:@"Website" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PointsMultiplier" index:0])
        {
            self.PointsMultiplier = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PointsMultiplier" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CSymbol" index:0])
        {
            self.CSymbol = [[KPUHelper getNode:__node name:@"CSymbol" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKResellerEmployeeID" index:0])
        {
            self.FKResellerEmployeeID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKResellerEmployeeID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SpendAvailable" index:0])
        {
            self.SpendAvailable = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"SpendAvailable" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __CredentialItemElement=[__request writeElement:Credential type:[KPUCredentialInfo class] name:@"Credential" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CredentialItemElement!=nil)
    {
        [self.Credential serialize:__CredentialItemElement __request: __request];
    }
             
    DDXMLElement* __DataStatsItemElement=[__request writeElement:DataStats type:[KPUDataStatInfo class] name:@"DataStats" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DataStatsItemElement!=nil)
    {
        [self.DataStats serialize:__DataStatsItemElement __request: __request];
    }
             
    DDXMLElement* __MakeAssistantToIdItemElement=[__request writeElement:@"MakeAssistantToId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__MakeAssistantToIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.MakeAssistantToId]];
             
    DDXMLElement* __UpdateCustomerItemElement=[__request writeElement:UpdateCustomer type:[KPUCustomerUpdateInfo class] name:@"UpdateCustomer" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UpdateCustomerItemElement!=nil)
    {
        [self.UpdateCustomer serialize:__UpdateCustomerItemElement __request: __request];
    }
             
    DDXMLElement* __objEmailDomainItemElement=[__request writeElement:objEmailDomain type:[KPUEmailDomainInfo class] name:@"objEmailDomain" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__objEmailDomainItemElement!=nil)
    {
        [self.objEmailDomain serialize:__objEmailDomainItemElement __request: __request];
    }
             
    DDXMLElement* __FKPaymentStatusIdItemElement=[__request writeElement:FKPaymentStatusId type:[NSNumber class] name:@"FKPaymentStatusId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKPaymentStatusIdItemElement!=nil)
    {
        [__FKPaymentStatusIdItemElement setStringValue:[self.FKPaymentStatusId stringValue]];
    }
             
    DDXMLElement* __PKCustomerIDItemElement=[__request writeElement:PKCustomerID type:[NSNumber class] name:@"PKCustomerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKCustomerIDItemElement!=nil)
    {
        [__PKCustomerIDItemElement setStringValue:[self.PKCustomerID stringValue]];
    }
             
    DDXMLElement* __FKCustomerIDItemElement=[__request writeElement:FKCustomerID type:[NSNumber class] name:@"FKCustomerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKCustomerIDItemElement!=nil)
    {
        [__FKCustomerIDItemElement setStringValue:[self.FKCustomerID stringValue]];
    }
             
    DDXMLElement* __TotalLoginsItemElement=[__request writeElement:@"TotalLogins" URI:@"http://www.apoyar.net/" parent:__parent];
    [__TotalLoginsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.TotalLogins]];
             
    DDXMLElement* __FKRecordStatIDItemElement=[__request writeElement:FKRecordStatID type:[NSNumber class] name:@"FKRecordStatID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKRecordStatIDItemElement!=nil)
    {
        [__FKRecordStatIDItemElement setStringValue:[self.FKRecordStatID stringValue]];
    }
             
    DDXMLElement* __FKCredentialIDItemElement=[__request writeElement:FKCredentialID type:[NSNumber class] name:@"FKCredentialID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKCredentialIDItemElement!=nil)
    {
        [__FKCredentialIDItemElement setStringValue:[self.FKCredentialID stringValue]];
    }
             
    DDXMLElement* __BusinessItemElement=[__request writeElement:@"Business" URI:@"http://www.apoyar.net/" parent:__parent];
    [__BusinessItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.Business]];
             
    DDXMLElement* __FirstNameItemElement=[__request writeElement:FirstName type:[NSString class] name:@"FirstName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__FirstNameItemElement!=nil)
    {
        [__FirstNameItemElement setStringValue:self.FirstName];
    }
             
    DDXMLElement* __MiddleNameItemElement=[__request writeElement:MiddleName type:[NSString class] name:@"MiddleName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__MiddleNameItemElement!=nil)
    {
        [__MiddleNameItemElement setStringValue:self.MiddleName];
    }
             
    DDXMLElement* __LastNameItemElement=[__request writeElement:LastName type:[NSString class] name:@"LastName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LastNameItemElement!=nil)
    {
        [__LastNameItemElement setStringValue:self.LastName];
    }
             
    DDXMLElement* __CreateTicketItemElement=[__request writeElement:@"CreateTicket" URI:@"http://www.apoyar.net/" parent:__parent];
    [__CreateTicketItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.CreateTicket]];
             
    DDXMLElement* __UpdateTicketItemElement=[__request writeElement:@"UpdateTicket" URI:@"http://www.apoyar.net/" parent:__parent];
    [__UpdateTicketItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.UpdateTicket]];
             
    DDXMLElement* __CloseticketItemElement=[__request writeElement:@"Closeticket" URI:@"http://www.apoyar.net/" parent:__parent];
    [__CloseticketItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.Closeticket]];
             
    DDXMLElement* __IsCoordinatorItemElement=[__request writeElement:@"IsCoordinator" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsCoordinatorItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsCoordinator]];
             
    DDXMLElement* __LastIPAddressItemElement=[__request writeElement:LastIPAddress type:[NSString class] name:@"LastIPAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LastIPAddressItemElement!=nil)
    {
        [__LastIPAddressItemElement setStringValue:self.LastIPAddress];
    }
             
    DDXMLElement* __VATNumberItemElement=[__request writeElement:VATNumber type:[NSString class] name:@"VATNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__VATNumberItemElement!=nil)
    {
        [__VATNumberItemElement setStringValue:self.VATNumber];
    }
             
    DDXMLElement* __LastWANIPItemElement=[__request writeElement:LastWANIP type:[NSString class] name:@"LastWANIP" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LastWANIPItemElement!=nil)
    {
        [__LastWANIPItemElement setStringValue:self.LastWANIP];
    }
             
    DDXMLElement* __OverruleItemElement=[__request writeElement:@"Overrule" URI:@"http://www.apoyar.net/" parent:__parent];
    [__OverruleItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.Overrule]];
             
    DDXMLElement* __IndustryItemElement=[__request writeElement:Industry type:[NSString class] name:@"Industry" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__IndustryItemElement!=nil)
    {
        [__IndustryItemElement setStringValue:self.Industry];
    }
             
    DDXMLElement* __CompanySizeItemElement=[__request writeElement:CompanySize type:[NSString class] name:@"CompanySize" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CompanySizeItemElement!=nil)
    {
        [__CompanySizeItemElement setStringValue:self.CompanySize];
    }
             
    DDXMLElement* __CreatedDatetimeItemElement=[__request writeElement:CreatedDatetime type:[NSDate class] name:@"CreatedDatetime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreatedDatetimeItemElement!=nil)
    {
        [__CreatedDatetimeItemElement setStringValue:[KPUHelper getStringFromDate:self.CreatedDatetime]];
    }
             
    DDXMLElement* __LastLoginTImeItemElement=[__request writeElement:LastLoginTIme type:[NSDate class] name:@"LastLoginTIme" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastLoginTImeItemElement!=nil)
    {
        [__LastLoginTImeItemElement setStringValue:[KPUHelper getStringFromDate:self.LastLoginTIme]];
    }
             
    DDXMLElement* __UserNameItemElement=[__request writeElement:UserName type:[NSString class] name:@"UserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserNameItemElement!=nil)
    {
        [__UserNameItemElement setStringValue:self.UserName];
    }
             
    DDXMLElement* __ISActiveItemElement=[__request writeElement:@"ISActive" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ISActiveItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.ISActive]];
             
    DDXMLElement* __RealNameItemElement=[__request writeElement:RealName type:[NSString class] name:@"RealName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__RealNameItemElement!=nil)
    {
        [__RealNameItemElement setStringValue:self.RealName];
    }
             
    DDXMLElement* __LocationItemElement=[__request writeElement:Location type:[NSString class] name:@"Location" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LocationItemElement!=nil)
    {
        [__LocationItemElement setStringValue:self.Location];
    }
             
    DDXMLElement* __IndividualCountItemElement=[__request writeElement:@"IndividualCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IndividualCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.IndividualCount]];
             
    DDXMLElement* __AssetCountItemElement=[__request writeElement:@"AssetCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AssetCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AssetCount]];
             
    DDXMLElement* __HasAssetItemElement=[__request writeElement:@"HasAsset" URI:@"http://www.apoyar.net/" parent:__parent];
    [__HasAssetItemElement setStringValue: [NSString stringWithFormat:@"%i", self.HasAsset]];
             
    DDXMLElement* __hasEmployeeItemElement=[__request writeElement:@"hasEmployee" URI:@"http://www.apoyar.net/" parent:__parent];
    [__hasEmployeeItemElement setStringValue: [NSString stringWithFormat:@"%i", self.hasEmployee]];
             
    DDXMLElement* __CreateUserItemElement=[__request writeElement:CreateUser type:[NSString class] name:@"CreateUser" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CreateUserItemElement!=nil)
    {
        [__CreateUserItemElement setStringValue:self.CreateUser];
    }
             
    DDXMLElement* __UpdateUserItemElement=[__request writeElement:UpdateUser type:[NSString class] name:@"UpdateUser" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UpdateUserItemElement!=nil)
    {
        [__UpdateUserItemElement setStringValue:self.UpdateUser];
    }
             
    DDXMLElement* __UpdatedDateTimeItemElement=[__request writeElement:UpdatedDateTime type:[NSDate class] name:@"UpdatedDateTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UpdatedDateTimeItemElement!=nil)
    {
        [__UpdatedDateTimeItemElement setStringValue:[KPUHelper getStringFromDate:self.UpdatedDateTime]];
    }
             
    DDXMLElement* __SupportLanguageItemElement=[__request writeElement:SupportLanguage type:[NSString class] name:@"SupportLanguage" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__SupportLanguageItemElement!=nil)
    {
        [__SupportLanguageItemElement setStringValue:self.SupportLanguage];
    }
             
    DDXMLElement* __SecurityRoleNameItemElement=[__request writeElement:SecurityRoleName type:[NSString class] name:@"SecurityRoleName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__SecurityRoleNameItemElement!=nil)
    {
        [__SecurityRoleNameItemElement setStringValue:self.SecurityRoleName];
    }
             
    DDXMLElement* __ResponseSLAItemElement=[__request writeElement:@"ResponseSLA" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ResponseSLAItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ResponseSLA]];
             
    DDXMLElement* __ResolutionSLAItemElement=[__request writeElement:@"ResolutionSLA" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ResolutionSLAItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ResolutionSLA]];
             
    DDXMLElement* __TeamViewerIdItemElement=[__request writeElement:TeamViewerId type:[NSString class] name:@"TeamViewerId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TeamViewerIdItemElement!=nil)
    {
        [__TeamViewerIdItemElement setStringValue:self.TeamViewerId];
    }
             
    DDXMLElement* __DefaultCurrencySymbolItemElement=[__request writeElement:DefaultCurrencySymbol type:[NSString class] name:@"DefaultCurrencySymbol" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DefaultCurrencySymbolItemElement!=nil)
    {
        [__DefaultCurrencySymbolItemElement setStringValue:self.DefaultCurrencySymbol];
    }
             
    DDXMLElement* __CurrencySymbolItemElement=[__request writeElement:CurrencySymbol type:[NSString class] name:@"CurrencySymbol" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CurrencySymbolItemElement!=nil)
    {
        [__CurrencySymbolItemElement setStringValue:self.CurrencySymbol];
    }
             
    DDXMLElement* __CurrencyCodeItemElement=[__request writeElement:CurrencyCode type:[NSString class] name:@"CurrencyCode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CurrencyCodeItemElement!=nil)
    {
        [__CurrencyCodeItemElement setStringValue:self.CurrencyCode];
    }
             
    DDXMLElement* __EmailAddressItemElement=[__request writeElement:EmailAddress type:[NSString class] name:@"EmailAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__EmailAddressItemElement!=nil)
    {
        [__EmailAddressItemElement setStringValue:self.EmailAddress];
    }
             
    DDXMLElement* __IsMobileItemElement=[__request writeElement:@"IsMobile" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsMobileItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsMobile]];
             
    DDXMLElement* __IsQualifiedItemElement=[__request writeElement:@"IsQualified" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsQualifiedItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsQualified]];
             
    DDXMLElement* __HitCountItemElement=[__request writeElement:@"HitCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__HitCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.HitCount]];
             
    DDXMLElement* __ContactTypeItemElement=[__request writeElement:ContactType type:[NSString class] name:@"ContactType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ContactTypeItemElement!=nil)
    {
        [__ContactTypeItemElement setStringValue:self.ContactType];
    }
             
    DDXMLElement* __CustomerNameItemElement=[__request writeElement:CustomerName type:[NSString class] name:@"CustomerName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CustomerNameItemElement!=nil)
    {
        [__CustomerNameItemElement setStringValue:self.CustomerName];
    }
             
    DDXMLElement* __EmployeeNameItemElement=[__request writeElement:EmployeeName type:[NSString class] name:@"EmployeeName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__EmployeeNameItemElement!=nil)
    {
        [__EmployeeNameItemElement setStringValue:self.EmployeeName];
    }
             
    DDXMLElement* __LastContactDateItemElement=[__request writeElement:LastContactDate type:[NSDate class] name:@"LastContactDate" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastContactDateItemElement!=nil)
    {
        [__LastContactDateItemElement setStringValue:[KPUHelper getStringFromDate:self.LastContactDate]];
    }
             
    DDXMLElement* __TicketCountItemElement=[__request writeElement:@"TicketCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__TicketCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.TicketCount]];
             
    DDXMLElement* __FKResellerIDItemElement=[__request writeElement:FKResellerID type:[NSNumber class] name:@"FKResellerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKResellerIDItemElement!=nil)
    {
        [__FKResellerIDItemElement setStringValue:[self.FKResellerID stringValue]];
    }
             
    DDXMLElement* __CustPhoneNumberItemElement=[__request writeElement:CustPhoneNumber type:[NSString class] name:@"CustPhoneNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CustPhoneNumberItemElement!=nil)
    {
        [__CustPhoneNumberItemElement setStringValue:self.CustPhoneNumber];
    }
             
    DDXMLElement* __FKDefaultAssetIDItemElement=[__request writeElement:FKDefaultAssetID type:[NSNumber class] name:@"FKDefaultAssetID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKDefaultAssetIDItemElement!=nil)
    {
        [__FKDefaultAssetIDItemElement setStringValue:[self.FKDefaultAssetID stringValue]];
    }
             
    DDXMLElement* __PayAsYouGoValidityItemElement=[__request writeElement:PayAsYouGoValidity type:[NSDate class] name:@"PayAsYouGoValidity" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PayAsYouGoValidityItemElement!=nil)
    {
        [__PayAsYouGoValidityItemElement setStringValue:[KPUHelper getStringFromDate:self.PayAsYouGoValidity]];
    }
             
    DDXMLElement* __PayAsYouGoBalanceItemElement=[__request writeElement:PayAsYouGoBalance type:[NSNumber class] name:@"PayAsYouGoBalance" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PayAsYouGoBalanceItemElement!=nil)
    {
        [__PayAsYouGoBalanceItemElement setStringValue:[self.PayAsYouGoBalance stringValue]];
    }
             
    DDXMLElement* __SubscriptionValidityItemElement=[__request writeElement:SubscriptionValidity type:[NSDate class] name:@"SubscriptionValidity" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__SubscriptionValidityItemElement!=nil)
    {
        [__SubscriptionValidityItemElement setStringValue:[KPUHelper getStringFromDate:self.SubscriptionValidity]];
    }
             
    DDXMLElement* __SubscriptionBalanceItemElement=[__request writeElement:SubscriptionBalance type:[NSNumber class] name:@"SubscriptionBalance" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__SubscriptionBalanceItemElement!=nil)
    {
        [__SubscriptionBalanceItemElement setStringValue:[self.SubscriptionBalance stringValue]];
    }
             
    DDXMLElement* __IsCreditApprovedItemElement=[__request writeElement:@"IsCreditApproved" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsCreditApprovedItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsCreditApproved]];
             
    DDXMLElement* __CreditAmountItemElement=[__request writeElement:CreditAmount type:[NSNumber class] name:@"CreditAmount" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreditAmountItemElement!=nil)
    {
        [__CreditAmountItemElement setStringValue:[self.CreditAmount stringValue]];
    }
             
    DDXMLElement* __LanguageNameItemElement=[__request writeElement:LanguageName type:[NSString class] name:@"LanguageName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LanguageNameItemElement!=nil)
    {
        [__LanguageNameItemElement setStringValue:self.LanguageName];
    }
             
    DDXMLElement* __PointsAvailableItemElement=[__request writeElement:PointsAvailable type:[NSString class] name:@"PointsAvailable" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PointsAvailableItemElement!=nil)
    {
        [__PointsAvailableItemElement setStringValue:self.PointsAvailable];
    }
             
    DDXMLElement* __LastUsedItemElement=[__request writeElement:LastUsed type:[NSDate class] name:@"LastUsed" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastUsedItemElement!=nil)
    {
        [__LastUsedItemElement setStringValue:[KPUHelper getStringFromDate:self.LastUsed]];
    }
             
    DDXMLElement* __CanBuyServicesItemElement=[__request writeElement:@"CanBuyServices" URI:@"http://www.apoyar.net/" parent:__parent];
    [__CanBuyServicesItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.CanBuyServices]];
             
    DDXMLElement* __CreditBalanceItemElement=[__request writeElement:CreditBalance type:[NSNumber class] name:@"CreditBalance" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreditBalanceItemElement!=nil)
    {
        [__CreditBalanceItemElement setStringValue:[self.CreditBalance stringValue]];
    }
             
    DDXMLElement* __AgentExchangeRateItemElement=[__request writeElement:AgentExchangeRate type:[NSNumber class] name:@"AgentExchangeRate" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__AgentExchangeRateItemElement!=nil)
    {
        [__AgentExchangeRateItemElement setStringValue:[self.AgentExchangeRate stringValue]];
    }
             
    DDXMLElement* __AccountNameItemElement=[__request writeElement:AccountName type:[NSString class] name:@"AccountName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__AccountNameItemElement!=nil)
    {
        [__AccountNameItemElement setStringValue:self.AccountName];
    }
             
    DDXMLElement* __PhoneNumberItemElement=[__request writeElement:PhoneNumber type:[NSString class] name:@"PhoneNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PhoneNumberItemElement!=nil)
    {
        [__PhoneNumberItemElement setStringValue:self.PhoneNumber];
    }
             
    DDXMLElement* __DefaultAssetNameItemElement=[__request writeElement:DefaultAssetName type:[NSString class] name:@"DefaultAssetName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DefaultAssetNameItemElement!=nil)
    {
        [__DefaultAssetNameItemElement setStringValue:self.DefaultAssetName];
    }
             
    DDXMLElement* __PointsPurchasedItemElement=[__request writeElement:@"PointsPurchased" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PointsPurchasedItemElement setStringValue: [NSString stringWithFormat:@"%i", self.PointsPurchased]];
             
    DDXMLElement* __TotalPointsSpentItemElement=[__request writeElement:@"TotalPointsSpent" URI:@"http://www.apoyar.net/" parent:__parent];
    [__TotalPointsSpentItemElement setStringValue: [NSString stringWithFormat:@"%i", self.TotalPointsSpent]];
             
    DDXMLElement* __MonthlyPointsSpentItemElement=[__request writeElement:@"MonthlyPointsSpent" URI:@"http://www.apoyar.net/" parent:__parent];
    [__MonthlyPointsSpentItemElement setStringValue: [NSString stringWithFormat:@"%i", self.MonthlyPointsSpent]];
             
    DDXMLElement* __YearlyPointsSpentItemElement=[__request writeElement:@"YearlyPointsSpent" URI:@"http://www.apoyar.net/" parent:__parent];
    [__YearlyPointsSpentItemElement setStringValue: [NSString stringWithFormat:@"%i", self.YearlyPointsSpent]];
             
    DDXMLElement* __PSATermItemElement=[__request writeElement:@"PSATerm" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PSATermItemElement setStringValue: [NSString stringWithFormat:@"%i", self.PSATerm]];
             
    DDXMLElement* __CreditExpireItemElement=[__request writeElement:CreditExpire type:[NSDate class] name:@"CreditExpire" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreditExpireItemElement!=nil)
    {
        [__CreditExpireItemElement setStringValue:[KPUHelper getStringFromDate:self.CreditExpire]];
    }
             
    DDXMLElement* __PaymentTermsItemElement=[__request writeElement:PaymentTerms type:[NSNumber class] name:@"PaymentTerms" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PaymentTermsItemElement!=nil)
    {
        [__PaymentTermsItemElement setStringValue:[self.PaymentTerms stringValue]];
    }
             
    DDXMLElement* __FKSecurityRoleIdItemElement=[__request writeElement:FKSecurityRoleId type:[NSNumber class] name:@"FKSecurityRoleId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKSecurityRoleIdItemElement!=nil)
    {
        [__FKSecurityRoleIdItemElement setStringValue:[self.FKSecurityRoleId stringValue]];
    }
             
    DDXMLElement* __FKMenuIdItemElement=[__request writeElement:@"FKMenuId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKMenuIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKMenuId]];
             
    DDXMLElement* __EmailForFreePointsItemElement=[__request writeElement:@"EmailForFreePoints" URI:@"http://www.apoyar.net/" parent:__parent];
    [__EmailForFreePointsItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.EmailForFreePoints]];
             
    DDXMLElement* __FKReferrerIDItemElement=[__request writeElement:@"FKReferrerID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKReferrerIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKReferrerID]];
             
    DDXMLElement* __FKEngineerIDItemElement=[__request writeElement:@"FKEngineerID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKEngineerIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKEngineerID]];
             
    DDXMLElement* __ResellerSupportEmailItemElement=[__request writeElement:ResellerSupportEmail type:[NSString class] name:@"ResellerSupportEmail" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ResellerSupportEmailItemElement!=nil)
    {
        [__ResellerSupportEmailItemElement setStringValue:self.ResellerSupportEmail];
    }
             
    DDXMLElement* __ResellerHasWebsiteItemElement=[__request writeElement:@"ResellerHasWebsite" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ResellerHasWebsiteItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.ResellerHasWebsite]];
             
    DDXMLElement* __ResellerWebsiteURLItemElement=[__request writeElement:ResellerWebsiteURL type:[NSString class] name:@"ResellerWebsiteURL" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ResellerWebsiteURLItemElement!=nil)
    {
        [__ResellerWebsiteURLItemElement setStringValue:self.ResellerWebsiteURL];
    }
             
    DDXMLElement* __PreferredExpertIDItemElement=[__request writeElement:@"PreferredExpertID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PreferredExpertIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.PreferredExpertID]];
             
    DDXMLElement* __PreferredExpertNameItemElement=[__request writeElement:PreferredExpertName type:[NSString class] name:@"PreferredExpertName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PreferredExpertNameItemElement!=nil)
    {
        [__PreferredExpertNameItemElement setStringValue:self.PreferredExpertName];
    }
             
    DDXMLElement* __ReferrerNameItemElement=[__request writeElement:ReferrerName type:[NSString class] name:@"ReferrerName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ReferrerNameItemElement!=nil)
    {
        [__ReferrerNameItemElement setStringValue:self.ReferrerName];
    }
             
    DDXMLElement* __ReferredByIDItemElement=[__request writeElement:@"ReferredByID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ReferredByIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ReferredByID]];
             
    DDXMLElement* __ReferredByUserTypeItemElement=[__request writeElement:@"ReferredByUserType" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ReferredByUserTypeItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ReferredByUserType]];
             
    DDXMLElement* __DefaultServicePointsItemElement=[__request writeElement:@"DefaultServicePoints" URI:@"http://www.apoyar.net/" parent:__parent];
    [__DefaultServicePointsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.DefaultServicePoints]];
             
    DDXMLElement* __FriendPointsItemElement=[__request writeElement:@"FriendPoints" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FriendPointsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FriendPoints]];
             
    DDXMLElement* __PointsawardedItemElement=[__request writeElement:@"Pointsawarded" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PointsawardedItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.Pointsawarded]];
             
    DDXMLElement* __CustomerResellerTypeItemElement=[__request writeElement:CustomerResellerType type:[NSNumber class] name:@"CustomerResellerType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CustomerResellerTypeItemElement!=nil)
    {
        [__CustomerResellerTypeItemElement setStringValue:[self.CustomerResellerType stringValue]];
    }
             
    DDXMLElement* __CountryCodeInfoItemElement=[__request writeElement:CountryCodeInfo type:[NSString class] name:@"CountryCodeInfo" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryCodeInfoItemElement!=nil)
    {
        [__CountryCodeInfoItemElement setStringValue:self.CountryCodeInfo];
    }
             
    DDXMLElement* __CountryCodeItemElement=[__request writeElement:CountryCode type:[NSString class] name:@"CountryCode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryCodeItemElement!=nil)
    {
        [__CountryCodeItemElement setStringValue:self.CountryCode];
    }
             
    DDXMLElement* __CompanyRegNoItemElement=[__request writeElement:CompanyRegNo type:[NSString class] name:@"CompanyRegNo" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CompanyRegNoItemElement!=nil)
    {
        [__CompanyRegNoItemElement setStringValue:self.CompanyRegNo];
    }
             
    DDXMLElement* __FkSellingSiteIDItemElement=[__request writeElement:@"FkSellingSiteID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FkSellingSiteIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FkSellingSiteID]];
             
    DDXMLElement* __CountryNameItemElement=[__request writeElement:CountryName type:[NSString class] name:@"CountryName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryNameItemElement!=nil)
    {
        [__CountryNameItemElement setStringValue:self.CountryName];
    }
             
    DDXMLElement* __KnownViaItemElement=[__request writeElement:KnownVia type:[NSString class] name:@"KnownVia" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__KnownViaItemElement!=nil)
    {
        [__KnownViaItemElement setStringValue:self.KnownVia];
    }
             
    DDXMLElement* __FunctionsItemElement=[__request writeElement:Functions type:[NSString class] name:@"Functions" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__FunctionsItemElement!=nil)
    {
        [__FunctionsItemElement setStringValue:self.Functions];
    }
             
    DDXMLElement* __CompanyNameItemElement=[__request writeElement:CompanyName type:[NSString class] name:@"CompanyName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CompanyNameItemElement!=nil)
    {
        [__CompanyNameItemElement setStringValue:self.CompanyName];
    }
             
    DDXMLElement* __WebsiteItemElement=[__request writeElement:Website type:[NSString class] name:@"Website" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__WebsiteItemElement!=nil)
    {
        [__WebsiteItemElement setStringValue:self.Website];
    }
             
    DDXMLElement* __PointsMultiplierItemElement=[__request writeElement:PointsMultiplier type:[NSNumber class] name:@"PointsMultiplier" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PointsMultiplierItemElement!=nil)
    {
        [__PointsMultiplierItemElement setStringValue:[self.PointsMultiplier stringValue]];
    }
             
    DDXMLElement* __CSymbolItemElement=[__request writeElement:CSymbol type:[NSString class] name:@"CSymbol" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CSymbolItemElement!=nil)
    {
        [__CSymbolItemElement setStringValue:self.CSymbol];
    }
             
    DDXMLElement* __FKResellerEmployeeIDItemElement=[__request writeElement:FKResellerEmployeeID type:[NSNumber class] name:@"FKResellerEmployeeID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKResellerEmployeeIDItemElement!=nil)
    {
        [__FKResellerEmployeeIDItemElement setStringValue:[self.FKResellerEmployeeID stringValue]];
    }
             
    DDXMLElement* __SpendAvailableItemElement=[__request writeElement:SpendAvailable type:[NSNumber class] name:@"SpendAvailable" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__SpendAvailableItemElement!=nil)
    {
        [__SpendAvailableItemElement setStringValue:[self.SpendAvailable stringValue]];
    }


}
@end
