//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUCredentialInfo.h"


@implementation KPUCredentialInfo
@synthesize PKCredentialID;
@synthesize UserName;
@synthesize UserPassword;
@synthesize EmailAddress;
@synthesize IsActive;
@synthesize FKLocationID;
@synthesize FKMenuId;
@synthesize LastLoginTime;
@synthesize StreetName1;
@synthesize StreetName2;
@synthesize BoxNumber;
@synthesize PostalCode;
@synthesize City;
@synthesize State;
@synthesize Country;
@synthesize PhoneNumber;
@synthesize Location;
@synthesize FKSupportLanguageId;
@synthesize ConfirmationKey;
@synthesize ConfirmEmail;
@synthesize ConfirmPassword;
@synthesize FKCountryID;
@synthesize CustomerID;
@synthesize EngineerID;
@synthesize ResellerID;
@synthesize CurrencyID;
@synthesize UserBankName;
@synthesize UserAccountNumber;
@synthesize UserSortCode;
@synthesize UserIBAN;
@synthesize UserBIC;
@synthesize UserSwift;
@synthesize UserABA;
@synthesize UserSpecialNarative;
@synthesize DefaultCurrencySymbol;
@synthesize InterfaceLanguage;
@synthesize Usercode;
@synthesize CountryName;
@synthesize RealName;
@synthesize Latitude;
@synthesize Longitude;
@synthesize FkSellingSiteID;
@synthesize AdminCompanyName;
@synthesize IsActivated;

+ (KPUCredentialInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKCredentialID =[NSNumber numberWithInt:0];
        self.FKLocationID =[NSNumber numberWithInt:0];
        self.FKMenuId =0;
        self.FKSupportLanguageId =[NSNumber numberWithInt:0];
        self.FKCountryID =[NSNumber numberWithInt:0];
        self.CustomerID =[NSNumber numberWithInt:0];
        self.EngineerID =[NSNumber numberWithInt:0];
        self.ResellerID =[NSNumber numberWithInt:0];
        self.CurrencyID =[NSNumber numberWithInt:0];
        self.Latitude =[NSNumber numberWithInt:0];
        self.Longitude =[NSNumber numberWithInt:0];
        self.FkSellingSiteID =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKCredentialID" index:0])
        {
            self.PKCredentialID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKCredentialID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UserName" index:0])
        {
            self.UserName = [[KPUHelper getNode:__node name:@"UserName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserPassword" index:0])
        {
            self.UserPassword = [[KPUHelper getNode:__node name:@"UserPassword" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"EmailAddress" index:0])
        {
            self.EmailAddress = [[KPUHelper getNode:__node name:@"EmailAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsActive" index:0])
        {
            self.IsActive = [[[KPUHelper getNode:__node name:@"IsActive" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"FKLocationID" index:0])
        {
            self.FKLocationID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKLocationID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKMenuId" index:0])
        {
            self.FKMenuId = [[[KPUHelper getNode:__node name:@"FKMenuId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"LastLoginTime" index:0])
        {
            self.LastLoginTime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastLoginTime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"StreetName1" index:0])
        {
            self.StreetName1 = [[KPUHelper getNode:__node name:@"StreetName1" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"StreetName2" index:0])
        {
            self.StreetName2 = [[KPUHelper getNode:__node name:@"StreetName2" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"BoxNumber" index:0])
        {
            self.BoxNumber = [[KPUHelper getNode:__node name:@"BoxNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PostalCode" index:0])
        {
            self.PostalCode = [[KPUHelper getNode:__node name:@"PostalCode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"City" index:0])
        {
            self.City = [[KPUHelper getNode:__node name:@"City" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"State" index:0])
        {
            self.State = [[KPUHelper getNode:__node name:@"State" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Country" index:0])
        {
            self.Country = [[KPUHelper getNode:__node name:@"Country" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"PhoneNumber" index:0])
        {
            self.PhoneNumber = [[KPUHelper getNode:__node name:@"PhoneNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Location" index:0])
        {
            self.Location = [[KPUHelper getNode:__node name:@"Location" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKSupportLanguageId" index:0])
        {
            self.FKSupportLanguageId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKSupportLanguageId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ConfirmationKey" index:0])
        {
            self.ConfirmationKey = [[KPUHelper getNode:__node name:@"ConfirmationKey" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ConfirmEmail" index:0])
        {
            self.ConfirmEmail = [[KPUHelper getNode:__node name:@"ConfirmEmail" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ConfirmPassword" index:0])
        {
            self.ConfirmPassword = [[KPUHelper getNode:__node name:@"ConfirmPassword" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKCountryID" index:0])
        {
            self.FKCountryID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKCountryID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CustomerID" index:0])
        {
            self.CustomerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CustomerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"EngineerID" index:0])
        {
            self.EngineerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"EngineerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ResellerID" index:0])
        {
            self.ResellerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"ResellerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CurrencyID" index:0])
        {
            self.CurrencyID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CurrencyID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UserBankName" index:0])
        {
            self.UserBankName = [[KPUHelper getNode:__node name:@"UserBankName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserAccountNumber" index:0])
        {
            self.UserAccountNumber = [[KPUHelper getNode:__node name:@"UserAccountNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserSortCode" index:0])
        {
            self.UserSortCode = [[KPUHelper getNode:__node name:@"UserSortCode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserIBAN" index:0])
        {
            self.UserIBAN = [[KPUHelper getNode:__node name:@"UserIBAN" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserBIC" index:0])
        {
            self.UserBIC = [[KPUHelper getNode:__node name:@"UserBIC" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserSwift" index:0])
        {
            self.UserSwift = [[KPUHelper getNode:__node name:@"UserSwift" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserABA" index:0])
        {
            self.UserABA = [[KPUHelper getNode:__node name:@"UserABA" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UserSpecialNarative" index:0])
        {
            self.UserSpecialNarative = [[KPUHelper getNode:__node name:@"UserSpecialNarative" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"DefaultCurrencySymbol" index:0])
        {
            self.DefaultCurrencySymbol = [[KPUHelper getNode:__node name:@"DefaultCurrencySymbol" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"InterfaceLanguage" index:0])
        {
            self.InterfaceLanguage = [[KPUHelper getNode:__node name:@"InterfaceLanguage" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Usercode" index:0])
        {
            self.Usercode = [[KPUHelper getNode:__node name:@"Usercode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CountryName" index:0])
        {
            self.CountryName = [[KPUHelper getNode:__node name:@"CountryName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"RealName" index:0])
        {
            self.RealName = [[KPUHelper getNode:__node name:@"RealName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Latitude" index:0])
        {
            self.Latitude = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Latitude" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Longitude" index:0])
        {
            self.Longitude = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Longitude" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FkSellingSiteID" index:0])
        {
            self.FkSellingSiteID = [[[KPUHelper getNode:__node name:@"FkSellingSiteID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AdminCompanyName" index:0])
        {
            self.AdminCompanyName = [[KPUHelper getNode:__node name:@"AdminCompanyName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsActivated" index:0])
        {
            self.IsActivated = [[[KPUHelper getNode:__node name:@"IsActivated" index:0] stringValue] boolValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKCredentialIDItemElement=[__request writeElement:PKCredentialID type:[NSNumber class] name:@"PKCredentialID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKCredentialIDItemElement!=nil)
    {
        [__PKCredentialIDItemElement setStringValue:[self.PKCredentialID stringValue]];
    }
             
    DDXMLElement* __UserNameItemElement=[__request writeElement:UserName type:[NSString class] name:@"UserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserNameItemElement!=nil)
    {
        [__UserNameItemElement setStringValue:self.UserName];
    }
             
    DDXMLElement* __UserPasswordItemElement=[__request writeElement:UserPassword type:[NSString class] name:@"UserPassword" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserPasswordItemElement!=nil)
    {
        [__UserPasswordItemElement setStringValue:self.UserPassword];
    }
             
    DDXMLElement* __EmailAddressItemElement=[__request writeElement:EmailAddress type:[NSString class] name:@"EmailAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__EmailAddressItemElement!=nil)
    {
        [__EmailAddressItemElement setStringValue:self.EmailAddress];
    }
             
    DDXMLElement* __IsActiveItemElement=[__request writeElement:@"IsActive" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsActiveItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsActive]];
             
    DDXMLElement* __FKLocationIDItemElement=[__request writeElement:FKLocationID type:[NSNumber class] name:@"FKLocationID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKLocationIDItemElement!=nil)
    {
        [__FKLocationIDItemElement setStringValue:[self.FKLocationID stringValue]];
    }
             
    DDXMLElement* __FKMenuIdItemElement=[__request writeElement:@"FKMenuId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKMenuIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKMenuId]];
             
    DDXMLElement* __LastLoginTimeItemElement=[__request writeElement:LastLoginTime type:[NSDate class] name:@"LastLoginTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastLoginTimeItemElement!=nil)
    {
        [__LastLoginTimeItemElement setStringValue:[KPUHelper getStringFromDate:self.LastLoginTime]];
    }
             
    DDXMLElement* __StreetName1ItemElement=[__request writeElement:StreetName1 type:[NSString class] name:@"StreetName1" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__StreetName1ItemElement!=nil)
    {
        [__StreetName1ItemElement setStringValue:self.StreetName1];
    }
             
    DDXMLElement* __StreetName2ItemElement=[__request writeElement:StreetName2 type:[NSString class] name:@"StreetName2" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__StreetName2ItemElement!=nil)
    {
        [__StreetName2ItemElement setStringValue:self.StreetName2];
    }
             
    DDXMLElement* __BoxNumberItemElement=[__request writeElement:BoxNumber type:[NSString class] name:@"BoxNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__BoxNumberItemElement!=nil)
    {
        [__BoxNumberItemElement setStringValue:self.BoxNumber];
    }
             
    DDXMLElement* __PostalCodeItemElement=[__request writeElement:PostalCode type:[NSString class] name:@"PostalCode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PostalCodeItemElement!=nil)
    {
        [__PostalCodeItemElement setStringValue:self.PostalCode];
    }
             
    DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CityItemElement!=nil)
    {
        [__CityItemElement setStringValue:self.City];
    }
             
    DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__StateItemElement!=nil)
    {
        [__StateItemElement setStringValue:self.State];
    }
             
    DDXMLElement* __CountryItemElement=[__request writeElement:Country type:[NSString class] name:@"Country" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryItemElement!=nil)
    {
        [__CountryItemElement setStringValue:self.Country];
    }
             
    DDXMLElement* __PhoneNumberItemElement=[__request writeElement:PhoneNumber type:[NSString class] name:@"PhoneNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PhoneNumberItemElement!=nil)
    {
        [__PhoneNumberItemElement setStringValue:self.PhoneNumber];
    }
             
    DDXMLElement* __LocationItemElement=[__request writeElement:Location type:[NSString class] name:@"Location" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LocationItemElement!=nil)
    {
        [__LocationItemElement setStringValue:self.Location];
    }
             
    DDXMLElement* __FKSupportLanguageIdItemElement=[__request writeElement:FKSupportLanguageId type:[NSNumber class] name:@"FKSupportLanguageId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKSupportLanguageIdItemElement!=nil)
    {
        [__FKSupportLanguageIdItemElement setStringValue:[self.FKSupportLanguageId stringValue]];
    }
             
    DDXMLElement* __ConfirmationKeyItemElement=[__request writeElement:ConfirmationKey type:[NSString class] name:@"ConfirmationKey" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ConfirmationKeyItemElement!=nil)
    {
        [__ConfirmationKeyItemElement setStringValue:self.ConfirmationKey];
    }
             
    DDXMLElement* __ConfirmEmailItemElement=[__request writeElement:ConfirmEmail type:[NSString class] name:@"ConfirmEmail" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ConfirmEmailItemElement!=nil)
    {
        [__ConfirmEmailItemElement setStringValue:self.ConfirmEmail];
    }
             
    DDXMLElement* __ConfirmPasswordItemElement=[__request writeElement:ConfirmPassword type:[NSString class] name:@"ConfirmPassword" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ConfirmPasswordItemElement!=nil)
    {
        [__ConfirmPasswordItemElement setStringValue:self.ConfirmPassword];
    }
             
    DDXMLElement* __FKCountryIDItemElement=[__request writeElement:FKCountryID type:[NSNumber class] name:@"FKCountryID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKCountryIDItemElement!=nil)
    {
        [__FKCountryIDItemElement setStringValue:[self.FKCountryID stringValue]];
    }
             
    DDXMLElement* __CustomerIDItemElement=[__request writeElement:CustomerID type:[NSNumber class] name:@"CustomerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CustomerIDItemElement!=nil)
    {
        [__CustomerIDItemElement setStringValue:[self.CustomerID stringValue]];
    }
             
    DDXMLElement* __EngineerIDItemElement=[__request writeElement:EngineerID type:[NSNumber class] name:@"EngineerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__EngineerIDItemElement!=nil)
    {
        [__EngineerIDItemElement setStringValue:[self.EngineerID stringValue]];
    }
             
    DDXMLElement* __ResellerIDItemElement=[__request writeElement:ResellerID type:[NSNumber class] name:@"ResellerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ResellerIDItemElement!=nil)
    {
        [__ResellerIDItemElement setStringValue:[self.ResellerID stringValue]];
    }
             
    DDXMLElement* __CurrencyIDItemElement=[__request writeElement:CurrencyID type:[NSNumber class] name:@"CurrencyID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CurrencyIDItemElement!=nil)
    {
        [__CurrencyIDItemElement setStringValue:[self.CurrencyID stringValue]];
    }
             
    DDXMLElement* __UserBankNameItemElement=[__request writeElement:UserBankName type:[NSString class] name:@"UserBankName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserBankNameItemElement!=nil)
    {
        [__UserBankNameItemElement setStringValue:self.UserBankName];
    }
             
    DDXMLElement* __UserAccountNumberItemElement=[__request writeElement:UserAccountNumber type:[NSString class] name:@"UserAccountNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserAccountNumberItemElement!=nil)
    {
        [__UserAccountNumberItemElement setStringValue:self.UserAccountNumber];
    }
             
    DDXMLElement* __UserSortCodeItemElement=[__request writeElement:UserSortCode type:[NSString class] name:@"UserSortCode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserSortCodeItemElement!=nil)
    {
        [__UserSortCodeItemElement setStringValue:self.UserSortCode];
    }
             
    DDXMLElement* __UserIBANItemElement=[__request writeElement:UserIBAN type:[NSString class] name:@"UserIBAN" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserIBANItemElement!=nil)
    {
        [__UserIBANItemElement setStringValue:self.UserIBAN];
    }
             
    DDXMLElement* __UserBICItemElement=[__request writeElement:UserBIC type:[NSString class] name:@"UserBIC" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserBICItemElement!=nil)
    {
        [__UserBICItemElement setStringValue:self.UserBIC];
    }
             
    DDXMLElement* __UserSwiftItemElement=[__request writeElement:UserSwift type:[NSString class] name:@"UserSwift" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserSwiftItemElement!=nil)
    {
        [__UserSwiftItemElement setStringValue:self.UserSwift];
    }
             
    DDXMLElement* __UserABAItemElement=[__request writeElement:UserABA type:[NSString class] name:@"UserABA" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserABAItemElement!=nil)
    {
        [__UserABAItemElement setStringValue:self.UserABA];
    }
             
    DDXMLElement* __UserSpecialNarativeItemElement=[__request writeElement:UserSpecialNarative type:[NSString class] name:@"UserSpecialNarative" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserSpecialNarativeItemElement!=nil)
    {
        [__UserSpecialNarativeItemElement setStringValue:self.UserSpecialNarative];
    }
             
    DDXMLElement* __DefaultCurrencySymbolItemElement=[__request writeElement:DefaultCurrencySymbol type:[NSString class] name:@"DefaultCurrencySymbol" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DefaultCurrencySymbolItemElement!=nil)
    {
        [__DefaultCurrencySymbolItemElement setStringValue:self.DefaultCurrencySymbol];
    }
             
    DDXMLElement* __InterfaceLanguageItemElement=[__request writeElement:InterfaceLanguage type:[NSString class] name:@"InterfaceLanguage" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__InterfaceLanguageItemElement!=nil)
    {
        [__InterfaceLanguageItemElement setStringValue:self.InterfaceLanguage];
    }
             
    DDXMLElement* __UsercodeItemElement=[__request writeElement:Usercode type:[NSString class] name:@"Usercode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UsercodeItemElement!=nil)
    {
        [__UsercodeItemElement setStringValue:self.Usercode];
    }
             
    DDXMLElement* __CountryNameItemElement=[__request writeElement:CountryName type:[NSString class] name:@"CountryName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryNameItemElement!=nil)
    {
        [__CountryNameItemElement setStringValue:self.CountryName];
    }
             
    DDXMLElement* __RealNameItemElement=[__request writeElement:RealName type:[NSString class] name:@"RealName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__RealNameItemElement!=nil)
    {
        [__RealNameItemElement setStringValue:self.RealName];
    }
             
    DDXMLElement* __LatitudeItemElement=[__request writeElement:Latitude type:[NSNumber class] name:@"Latitude" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LatitudeItemElement!=nil)
    {
        [__LatitudeItemElement setStringValue:[self.Latitude stringValue]];
    }
             
    DDXMLElement* __LongitudeItemElement=[__request writeElement:Longitude type:[NSNumber class] name:@"Longitude" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LongitudeItemElement!=nil)
    {
        [__LongitudeItemElement setStringValue:[self.Longitude stringValue]];
    }
             
    DDXMLElement* __FkSellingSiteIDItemElement=[__request writeElement:@"FkSellingSiteID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FkSellingSiteIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FkSellingSiteID]];
             
    DDXMLElement* __AdminCompanyNameItemElement=[__request writeElement:AdminCompanyName type:[NSString class] name:@"AdminCompanyName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__AdminCompanyNameItemElement!=nil)
    {
        [__AdminCompanyNameItemElement setStringValue:self.AdminCompanyName];
    }
             
    DDXMLElement* __IsActivatedItemElement=[__request writeElement:@"IsActivated" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsActivatedItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsActivated]];


}
@end
