//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUCredentialInfo;
@class KPUDataStatInfo;
@class KPUCustomerUpdateInfo;
@class KPUEmailDomainInfo;
@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUCustomerInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getCredential) KPUCredentialInfo* Credential;

@property (retain,nonatomic,getter=getDataStats) KPUDataStatInfo* DataStats;

@property (nonatomic,getter=getMakeAssistantToId) int MakeAssistantToId;

@property (retain,nonatomic,getter=getUpdateCustomer) KPUCustomerUpdateInfo* UpdateCustomer;

@property (retain,nonatomic,getter=getObjEmailDomain) KPUEmailDomainInfo* objEmailDomain;

@property (retain,nonatomic,getter=getFKPaymentStatusId) NSNumber* FKPaymentStatusId;

@property (retain,nonatomic,getter=getPKCustomerID) NSNumber* PKCustomerID;

@property (retain,nonatomic,getter=getFKCustomerID) NSNumber* FKCustomerID;

@property (nonatomic,getter=getTotalLogins) int TotalLogins;

@property (retain,nonatomic,getter=getFKRecordStatID) NSNumber* FKRecordStatID;

@property (retain,nonatomic,getter=getFKCredentialID) NSNumber* FKCredentialID;

@property (nonatomic,getter=getBusiness) BOOL Business;

@property (retain,nonatomic,getter=getFirstName) NSString* FirstName;

@property (retain,nonatomic,getter=getMiddleName) NSString* MiddleName;

@property (retain,nonatomic,getter=getLastName) NSString* LastName;

@property (nonatomic,getter=getCreateTicket) BOOL CreateTicket;

@property (nonatomic,getter=getUpdateTicket) BOOL UpdateTicket;

@property (nonatomic,getter=getCloseticket) BOOL Closeticket;

@property (nonatomic,getter=getIsCoordinator) BOOL IsCoordinator;

@property (retain,nonatomic,getter=getLastIPAddress) NSString* LastIPAddress;

@property (retain,nonatomic,getter=getVATNumber) NSString* VATNumber;

@property (retain,nonatomic,getter=getLastWANIP) NSString* LastWANIP;

@property (nonatomic,getter=getOverrule) BOOL Overrule;

@property (retain,nonatomic,getter=getIndustry) NSString* Industry;

@property (retain,nonatomic,getter=getCompanySize) NSString* CompanySize;

@property (retain,nonatomic,getter=getCreatedDatetime) NSDate* CreatedDatetime;

@property (retain,nonatomic,getter=getLastLoginTIme) NSDate* LastLoginTIme;

@property (retain,nonatomic,getter=getUserName) NSString* UserName;

@property (nonatomic,getter=getISActive) BOOL ISActive;

@property (retain,nonatomic,getter=getRealName) NSString* RealName;

@property (retain,nonatomic,getter=getLocation) NSString* Location;

@property (nonatomic,getter=getIndividualCount) int IndividualCount;

@property (nonatomic,getter=getAssetCount) int AssetCount;

@property (nonatomic,getter=getHasAsset) int HasAsset;

@property (nonatomic,getter=getHasEmployee) int hasEmployee;

@property (retain,nonatomic,getter=getCreateUser) NSString* CreateUser;

@property (retain,nonatomic,getter=getUpdateUser) NSString* UpdateUser;

@property (retain,nonatomic,getter=getUpdatedDateTime) NSDate* UpdatedDateTime;

@property (retain,nonatomic,getter=getSupportLanguage) NSString* SupportLanguage;

@property (retain,nonatomic,getter=getSecurityRoleName) NSString* SecurityRoleName;

@property (nonatomic,getter=getResponseSLA) int ResponseSLA;

@property (nonatomic,getter=getResolutionSLA) int ResolutionSLA;

@property (retain,nonatomic,getter=getTeamViewerId) NSString* TeamViewerId;

@property (retain,nonatomic,getter=getDefaultCurrencySymbol) NSString* DefaultCurrencySymbol;

@property (retain,nonatomic,getter=getCurrencySymbol) NSString* CurrencySymbol;

@property (retain,nonatomic,getter=getCurrencyCode) NSString* CurrencyCode;

@property (retain,nonatomic,getter=getEmailAddress) NSString* EmailAddress;

@property (nonatomic,getter=getIsMobile) BOOL IsMobile;

@property (nonatomic,getter=getIsQualified) BOOL IsQualified;

@property (nonatomic,getter=getHitCount) int HitCount;

@property (retain,nonatomic,getter=getContactType) NSString* ContactType;

@property (retain,nonatomic,getter=getCustomerName) NSString* CustomerName;

@property (retain,nonatomic,getter=getEmployeeName) NSString* EmployeeName;

@property (retain,nonatomic,getter=getLastContactDate) NSDate* LastContactDate;

@property (nonatomic,getter=getTicketCount) int TicketCount;

@property (retain,nonatomic,getter=getFKResellerID) NSNumber* FKResellerID;

@property (retain,nonatomic,getter=getCustPhoneNumber) NSString* CustPhoneNumber;

@property (retain,nonatomic,getter=getFKDefaultAssetID) NSNumber* FKDefaultAssetID;

@property (retain,nonatomic,getter=getPayAsYouGoValidity) NSDate* PayAsYouGoValidity;

@property (retain,nonatomic,getter=getPayAsYouGoBalance) NSNumber* PayAsYouGoBalance;

@property (retain,nonatomic,getter=getSubscriptionValidity) NSDate* SubscriptionValidity;

@property (retain,nonatomic,getter=getSubscriptionBalance) NSNumber* SubscriptionBalance;

@property (nonatomic,getter=getIsCreditApproved) BOOL IsCreditApproved;

@property (retain,nonatomic,getter=getCreditAmount) NSNumber* CreditAmount;

@property (retain,nonatomic,getter=getLanguageName) NSString* LanguageName;

@property (retain,nonatomic,getter=getPointsAvailable) NSString* PointsAvailable;

@property (retain,nonatomic,getter=getLastUsed) NSDate* LastUsed;

@property (nonatomic,getter=getCanBuyServices) BOOL CanBuyServices;

@property (retain,nonatomic,getter=getCreditBalance) NSNumber* CreditBalance;

@property (retain,nonatomic,getter=getAgentExchangeRate) NSNumber* AgentExchangeRate;

@property (retain,nonatomic,getter=getAccountName) NSString* AccountName;

@property (retain,nonatomic,getter=getPhoneNumber) NSString* PhoneNumber;

@property (retain,nonatomic,getter=getDefaultAssetName) NSString* DefaultAssetName;

@property (nonatomic,getter=getPointsPurchased) int PointsPurchased;

@property (nonatomic,getter=getTotalPointsSpent) int TotalPointsSpent;

@property (nonatomic,getter=getMonthlyPointsSpent) int MonthlyPointsSpent;

@property (nonatomic,getter=getYearlyPointsSpent) int YearlyPointsSpent;

@property (nonatomic,getter=getPSATerm) int PSATerm;

@property (retain,nonatomic,getter=getCreditExpire) NSDate* CreditExpire;

@property (retain,nonatomic,getter=getPaymentTerms) NSNumber* PaymentTerms;

@property (retain,nonatomic,getter=getFKSecurityRoleId) NSNumber* FKSecurityRoleId;

@property (nonatomic,getter=getFKMenuId) int FKMenuId;

@property (nonatomic,getter=getEmailForFreePoints) BOOL EmailForFreePoints;

@property (nonatomic,getter=getFKReferrerID) int FKReferrerID;

@property (nonatomic,getter=getFKEngineerID) int FKEngineerID;

@property (retain,nonatomic,getter=getResellerSupportEmail) NSString* ResellerSupportEmail;

@property (nonatomic,getter=getResellerHasWebsite) BOOL ResellerHasWebsite;

@property (retain,nonatomic,getter=getResellerWebsiteURL) NSString* ResellerWebsiteURL;

@property (nonatomic,getter=getPreferredExpertID) int PreferredExpertID;

@property (retain,nonatomic,getter=getPreferredExpertName) NSString* PreferredExpertName;

@property (retain,nonatomic,getter=getReferrerName) NSString* ReferrerName;

@property (nonatomic,getter=getReferredByID) int ReferredByID;

@property (nonatomic,getter=getReferredByUserType) int ReferredByUserType;

@property (nonatomic,getter=getDefaultServicePoints) int DefaultServicePoints;

@property (nonatomic,getter=getFriendPoints) int FriendPoints;

@property (nonatomic,getter=getPointsawarded) BOOL Pointsawarded;

@property (retain,nonatomic,getter=getCustomerResellerType) NSNumber* CustomerResellerType;

@property (retain,nonatomic,getter=getCountryCodeInfo) NSString* CountryCodeInfo;

@property (retain,nonatomic,getter=getCountryCode) NSString* CountryCode;

@property (retain,nonatomic,getter=getCompanyRegNo) NSString* CompanyRegNo;

@property (nonatomic,getter=getFkSellingSiteID) int FkSellingSiteID;

@property (retain,nonatomic,getter=getCountryName) NSString* CountryName;

@property (retain,nonatomic,getter=getKnownVia) NSString* KnownVia;

@property (retain,nonatomic,getter=getFunctions) NSString* Functions;

@property (retain,nonatomic,getter=getCompanyName) NSString* CompanyName;

@property (retain,nonatomic,getter=getWebsite) NSString* Website;

@property (retain,nonatomic,getter=getPointsMultiplier) NSNumber* PointsMultiplier;

@property (retain,nonatomic,getter=getCSymbol) NSString* CSymbol;

@property (retain,nonatomic,getter=getFKResellerEmployeeID) NSNumber* FKResellerEmployeeID;

@property (retain,nonatomic,getter=getSpendAvailable) NSNumber* SpendAvailable;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUCustomerInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end