//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUContractInfo.h"


@implementation KPUContractInfo
@synthesize PKContractID;
@synthesize ContractName;
@synthesize FileExtension;

+ (KPUContractInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKContractID =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKContractID" index:0])
        {
            self.PKContractID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKContractID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ContractName" index:0])
        {
            self.ContractName = [[KPUHelper getNode:__node name:@"ContractName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FileExtension" index:0])
        {
            self.FileExtension = [[KPUHelper getNode:__node name:@"FileExtension" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKContractIDItemElement=[__request writeElement:PKContractID type:[NSNumber class] name:@"PKContractID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKContractIDItemElement!=nil)
    {
        [__PKContractIDItemElement setStringValue:[self.PKContractID stringValue]];
    }
             
    DDXMLElement* __ContractNameItemElement=[__request writeElement:ContractName type:[NSString class] name:@"ContractName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ContractNameItemElement!=nil)
    {
        [__ContractNameItemElement setStringValue:self.ContractName];
    }
             
    DDXMLElement* __FileExtensionItemElement=[__request writeElement:FileExtension type:[NSString class] name:@"FileExtension" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__FileExtensionItemElement!=nil)
    {
        [__FileExtensionItemElement setStringValue:self.FileExtension];
    }


}
@end
