//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUUserType.h"
#import "KPUDataStatInfo.h"


@implementation KPUDataStatInfo
@synthesize PKRecordStatID;
@synthesize CreatedBy;
@synthesize UpdatedBy;
@synthesize CreatedDateTime;
@synthesize UpdatedDateTime;
@synthesize CreatedUserType;
@synthesize UpdatedUserType;
@synthesize CreatedUserName;
@synthesize UpdatedUserName;

+ (KPUDataStatInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKRecordStatID =[NSNumber numberWithInt:0];
        self.CreatedBy =[NSNumber numberWithInt:0];
        self.UpdatedBy =[NSNumber numberWithInt:0];
        self.CreatedUserType =KPUUserType.ResellerOrExpert;
        self.UpdatedUserType =KPUUserType.ResellerOrExpert;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKRecordStatID" index:0])
        {
            self.PKRecordStatID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKRecordStatID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CreatedBy" index:0])
        {
            self.CreatedBy = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CreatedBy" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedBy" index:0])
        {
            self.UpdatedBy = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"UpdatedBy" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CreatedDateTime" index:0])
        {
            self.CreatedDateTime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"CreatedDateTime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedDateTime" index:0])
        {
            self.UpdatedDateTime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"UpdatedDateTime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CreatedUserType" index:0])
        {
            self.CreatedUserType = (KPUUserType*)[KPUUserType createWithXml:[KPUHelper getNode:__node name:@"CreatedUserType" index:0]];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedUserType" index:0])
        {
            self.UpdatedUserType = (KPUUserType*)[KPUUserType createWithXml:[KPUHelper getNode:__node name:@"UpdatedUserType" index:0]];
        }
        if([KPUHelper hasValue:__node name:@"CreatedUserName" index:0])
        {
            self.CreatedUserName = [[KPUHelper getNode:__node name:@"CreatedUserName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedUserName" index:0])
        {
            self.UpdatedUserName = [[KPUHelper getNode:__node name:@"UpdatedUserName" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKRecordStatIDItemElement=[__request writeElement:PKRecordStatID type:[NSNumber class] name:@"PKRecordStatID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKRecordStatIDItemElement!=nil)
    {
        [__PKRecordStatIDItemElement setStringValue:[self.PKRecordStatID stringValue]];
    }
             
    DDXMLElement* __CreatedByItemElement=[__request writeElement:CreatedBy type:[NSNumber class] name:@"CreatedBy" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreatedByItemElement!=nil)
    {
        [__CreatedByItemElement setStringValue:[self.CreatedBy stringValue]];
    }
             
    DDXMLElement* __UpdatedByItemElement=[__request writeElement:UpdatedBy type:[NSNumber class] name:@"UpdatedBy" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UpdatedByItemElement!=nil)
    {
        [__UpdatedByItemElement setStringValue:[self.UpdatedBy stringValue]];
    }
             
    DDXMLElement* __CreatedDateTimeItemElement=[__request writeElement:CreatedDateTime type:[NSDate class] name:@"CreatedDateTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreatedDateTimeItemElement!=nil)
    {
        [__CreatedDateTimeItemElement setStringValue:[KPUHelper getStringFromDate:self.CreatedDateTime]];
    }
             
    DDXMLElement* __UpdatedDateTimeItemElement=[__request writeElement:UpdatedDateTime type:[NSDate class] name:@"UpdatedDateTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UpdatedDateTimeItemElement!=nil)
    {
        [__UpdatedDateTimeItemElement setStringValue:[KPUHelper getStringFromDate:self.UpdatedDateTime]];
    }
             
    DDXMLElement* __CreatedUserTypeItemElement=[__request writeElement:CreatedUserType type:[KPUUserType class] name:@"CreatedUserType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreatedUserTypeItemElement!=nil)
    {
        [self.CreatedUserType serialize:__CreatedUserTypeItemElement];
    }
             
    DDXMLElement* __UpdatedUserTypeItemElement=[__request writeElement:UpdatedUserType type:[KPUUserType class] name:@"UpdatedUserType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UpdatedUserTypeItemElement!=nil)
    {
        [self.UpdatedUserType serialize:__UpdatedUserTypeItemElement];
    }
             
    DDXMLElement* __CreatedUserNameItemElement=[__request writeElement:CreatedUserName type:[NSString class] name:@"CreatedUserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CreatedUserNameItemElement!=nil)
    {
        [__CreatedUserNameItemElement setStringValue:self.CreatedUserName];
    }
             
    DDXMLElement* __UpdatedUserNameItemElement=[__request writeElement:UpdatedUserName type:[NSString class] name:@"UpdatedUserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UpdatedUserNameItemElement!=nil)
    {
        [__UpdatedUserNameItemElement setStringValue:self.UpdatedUserName];
    }


}
@end
