//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
@class KPUUserType;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUDataStatInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getPKRecordStatID) NSNumber* PKRecordStatID;

@property (retain,nonatomic,getter=getCreatedBy) NSNumber* CreatedBy;

@property (retain,nonatomic,getter=getUpdatedBy) NSNumber* UpdatedBy;

@property (retain,nonatomic,getter=getCreatedDateTime) NSDate* CreatedDateTime;

@property (retain,nonatomic,getter=getUpdatedDateTime) NSDate* UpdatedDateTime;

@property (retain,nonatomic,getter=getCreatedUserType) KPUUserType* CreatedUserType;

@property (retain,nonatomic,getter=getUpdatedUserType) KPUUserType* UpdatedUserType;

@property (retain,nonatomic,getter=getCreatedUserName) NSString* CreatedUserName;

@property (retain,nonatomic,getter=getUpdatedUserName) NSString* UpdatedUserName;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUDataStatInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end