//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUEmailDomainInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getPKEmailDomainId) NSNumber* PKEmailDomainId;

@property (retain,nonatomic,getter=getEmailDomainName) NSString* EmailDomainName;

@property (retain,nonatomic,getter=getFkCustomerId) NSNumber* FkCustomerId;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUEmailDomainInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end