//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUDataStatInfo.h"
#import "KPUCredentialInfo.h"
#import "KPUEngineerUpdateInfo.h"
#import "KPUHelper.h"
#import "KPUEngineerInfo.h"


@implementation KPUEngineerInfo
@synthesize DataStat;
@synthesize Credential;
@synthesize DepartmentId;
@synthesize UpdateEngineer;
@synthesize PKEngineerID;
@synthesize Rating;
@synthesize Photo;
@synthesize FKRecordStatID;
@synthesize FKCredentialID;
@synthesize FirstName;
@synthesize MiddleName;
@synthesize LastName;
@synthesize AgentPIN;
@synthesize AgentType;
@synthesize LastIPAddress;
@synthesize CreatedDatetime;
@synthesize LastLoginTIme;
@synthesize UserName;
@synthesize ISActive;
@synthesize RealName;
@synthesize isUpdateEmail;
@synthesize CreateUser;
@synthesize UpdateUser;
@synthesize UpdatedDateTime;
@synthesize SupportLanguage;
@synthesize SecurityRoleName;
@synthesize TicketsCount;
@synthesize UserRating;
@synthesize FKLanguage1ID;
@synthesize FKLanguage2ID;
@synthesize FKLanguage3ID;
@synthesize FKLanguage4ID;
@synthesize ReceivedPassport;
@synthesize ReceivedScannedDocument;
@synthesize VerifiedHomeAddress;
@synthesize CV;
@synthesize VerifiedBy;
@synthesize VerifiedByType;
@synthesize VerifiedDate;
@synthesize InterviewDate1;
@synthesize InterviewPerson1;
@synthesize InterviewPersonType1;
@synthesize InterviewPersonResult1;
@synthesize InterviewDate2;
@synthesize InterviewPerson2;
@synthesize InterviewPersonType2;
@synthesize InterviewPersonResult2;
@synthesize ActivationStatus;
@synthesize AvgResolutionL1;
@synthesize AvgResolutionL2;
@synthesize AvgResolutionL3;
@synthesize AvgResolveL1;
@synthesize AvgResolveL2;
@synthesize AvgResolveL3;
@synthesize ScreenName;
@synthesize ISPName;
@synthesize IPAddress;
@synthesize ReferenceName;
@synthesize ReferencePhoneNumber;
@synthesize ReferenceEmailAddress;
@synthesize FKCurrencyID;
@synthesize MonthlyPoints;
@synthesize YearlyPoints;
@synthesize LastPaid;
@synthesize CurrencySymbol;
@synthesize Amount;
@synthesize FKCountryID;
@synthesize IsSkills;
@synthesize PreferedInterviewTime;
@synthesize AlternativeTelephoneNumber;
@synthesize FKResellerID;
@synthesize FKEMPEngineerID;
@synthesize FKSecurityRoleId;
@synthesize FKMenuId;
@synthesize ReferenceCode;
@synthesize isLogged;
@synthesize CountryName;

+ (KPUEngineerInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.DepartmentId =0;
        self.PKEngineerID =[NSNumber numberWithInt:0];
        self.Rating =[NSNumber numberWithInt:0];
        self.FKRecordStatID =[NSNumber numberWithInt:0];
        self.FKCredentialID =[NSNumber numberWithInt:0];
        self.AgentType =[NSNumber numberWithInt:0];
        self.TicketsCount =0;
        self.UserRating =[NSNumber numberWithInt:0];
        self.FKLanguage1ID =[NSNumber numberWithInt:0];
        self.FKLanguage2ID =[NSNumber numberWithInt:0];
        self.FKLanguage3ID =[NSNumber numberWithInt:0];
        self.FKLanguage4ID =[NSNumber numberWithInt:0];
        self.VerifiedBy =[NSNumber numberWithInt:0];
        self.VerifiedByType =0;
        self.InterviewPerson1 =[NSNumber numberWithInt:0];
        self.InterviewPersonType1 =0;
        self.InterviewPersonResult1 =0;
        self.InterviewPerson2 =[NSNumber numberWithInt:0];
        self.InterviewPersonType2 =0;
        self.InterviewPersonResult2 =0;
        self.ActivationStatus =0;
        self.AvgResolutionL1 =0;
        self.AvgResolutionL2 =0;
        self.AvgResolutionL3 =0;
        self.AvgResolveL1 =0;
        self.AvgResolveL2 =0;
        self.AvgResolveL3 =0;
        self.FKCurrencyID =0;
        self.FKCountryID =[NSNumber numberWithInt:0];
        self.FKResellerID =[NSNumber numberWithInt:0];
        self.FKEMPEngineerID =0;
        self.FKSecurityRoleId =[NSNumber numberWithInt:0];
        self.FKMenuId =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"DataStat" index:0])
        {
            self.DataStat = (KPUDataStatInfo*)[__request createObject:[KPUHelper getNode:__node name:@"DataStat" index:0] type:[KPUDataStatInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"Credential" index:0])
        {
            self.Credential = (KPUCredentialInfo*)[__request createObject:[KPUHelper getNode:__node name:@"Credential" index:0] type:[KPUCredentialInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"DepartmentId" index:0])
        {
            self.DepartmentId = [[[KPUHelper getNode:__node name:@"DepartmentId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdateEngineer" index:0])
        {
            self.UpdateEngineer = (KPUEngineerUpdateInfo*)[__request createObject:[KPUHelper getNode:__node name:@"UpdateEngineer" index:0] type:[KPUEngineerUpdateInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"PKEngineerID" index:0])
        {
            self.PKEngineerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKEngineerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Rating" index:0])
        {
            self.Rating = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Rating" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Photo" index:0])
        {
            self.Photo = [[KPUHelper getNode:__node name:@"Photo" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKRecordStatID" index:0])
        {
            self.FKRecordStatID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKRecordStatID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKCredentialID" index:0])
        {
            self.FKCredentialID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKCredentialID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FirstName" index:0])
        {
            self.FirstName = [[KPUHelper getNode:__node name:@"FirstName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"MiddleName" index:0])
        {
            self.MiddleName = [[KPUHelper getNode:__node name:@"MiddleName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastName" index:0])
        {
            self.LastName = [[KPUHelper getNode:__node name:@"LastName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"AgentPIN" index:0])
        {
            self.AgentPIN = [[KPUHelper getNode:__node name:@"AgentPIN" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"AgentType" index:0])
        {
            self.AgentType = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"AgentType" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"LastIPAddress" index:0])
        {
            self.LastIPAddress = [[KPUHelper getNode:__node name:@"LastIPAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"CreatedDatetime" index:0])
        {
            self.CreatedDatetime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"CreatedDatetime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"LastLoginTIme" index:0])
        {
            self.LastLoginTIme = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastLoginTIme" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"UserName" index:0])
        {
            self.UserName = [[KPUHelper getNode:__node name:@"UserName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ISActive" index:0])
        {
            self.ISActive = [[[KPUHelper getNode:__node name:@"ISActive" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"RealName" index:0])
        {
            self.RealName = [[KPUHelper getNode:__node name:@"RealName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"isUpdateEmail" index:0])
        {
            self.isUpdateEmail = [[[KPUHelper getNode:__node name:@"isUpdateEmail" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CreateUser" index:0])
        {
            self.CreateUser = [[KPUHelper getNode:__node name:@"CreateUser" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdateUser" index:0])
        {
            self.UpdateUser = [[KPUHelper getNode:__node name:@"UpdateUser" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"UpdatedDateTime" index:0])
        {
            self.UpdatedDateTime = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"UpdatedDateTime" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SupportLanguage" index:0])
        {
            self.SupportLanguage = [[KPUHelper getNode:__node name:@"SupportLanguage" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"SecurityRoleName" index:0])
        {
            self.SecurityRoleName = [[KPUHelper getNode:__node name:@"SecurityRoleName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketsCount" index:0])
        {
            self.TicketsCount = [[[KPUHelper getNode:__node name:@"TicketsCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"UserRating" index:0])
        {
            self.UserRating = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"UserRating" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKLanguage1ID" index:0])
        {
            self.FKLanguage1ID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKLanguage1ID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKLanguage2ID" index:0])
        {
            self.FKLanguage2ID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKLanguage2ID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKLanguage3ID" index:0])
        {
            self.FKLanguage3ID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKLanguage3ID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKLanguage4ID" index:0])
        {
            self.FKLanguage4ID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKLanguage4ID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ReceivedPassport" index:0])
        {
            self.ReceivedPassport = [[[KPUHelper getNode:__node name:@"ReceivedPassport" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"ReceivedScannedDocument" index:0])
        {
            self.ReceivedScannedDocument = [[[KPUHelper getNode:__node name:@"ReceivedScannedDocument" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"VerifiedHomeAddress" index:0])
        {
            self.VerifiedHomeAddress = [[[KPUHelper getNode:__node name:@"VerifiedHomeAddress" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CV" index:0])
        {
            self.CV = [[[KPUHelper getNode:__node name:@"CV" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"VerifiedBy" index:0])
        {
            self.VerifiedBy = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"VerifiedBy" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"VerifiedByType" index:0])
        {
            self.VerifiedByType = [[[KPUHelper getNode:__node name:@"VerifiedByType" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"VerifiedDate" index:0])
        {
            self.VerifiedDate = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"VerifiedDate" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"InterviewDate1" index:0])
        {
            self.InterviewDate1 = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"InterviewDate1" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPerson1" index:0])
        {
            self.InterviewPerson1 = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"InterviewPerson1" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPersonType1" index:0])
        {
            self.InterviewPersonType1 = [[[KPUHelper getNode:__node name:@"InterviewPersonType1" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPersonResult1" index:0])
        {
            self.InterviewPersonResult1 = [[[KPUHelper getNode:__node name:@"InterviewPersonResult1" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"InterviewDate2" index:0])
        {
            self.InterviewDate2 = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"InterviewDate2" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPerson2" index:0])
        {
            self.InterviewPerson2 = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"InterviewPerson2" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPersonType2" index:0])
        {
            self.InterviewPersonType2 = [[[KPUHelper getNode:__node name:@"InterviewPersonType2" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"InterviewPersonResult2" index:0])
        {
            self.InterviewPersonResult2 = [[[KPUHelper getNode:__node name:@"InterviewPersonResult2" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ActivationStatus" index:0])
        {
            self.ActivationStatus = [[[KPUHelper getNode:__node name:@"ActivationStatus" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolutionL1" index:0])
        {
            self.AvgResolutionL1 = [[[KPUHelper getNode:__node name:@"AvgResolutionL1" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolutionL2" index:0])
        {
            self.AvgResolutionL2 = [[[KPUHelper getNode:__node name:@"AvgResolutionL2" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolutionL3" index:0])
        {
            self.AvgResolutionL3 = [[[KPUHelper getNode:__node name:@"AvgResolutionL3" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolveL1" index:0])
        {
            self.AvgResolveL1 = [[[KPUHelper getNode:__node name:@"AvgResolveL1" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolveL2" index:0])
        {
            self.AvgResolveL2 = [[[KPUHelper getNode:__node name:@"AvgResolveL2" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AvgResolveL3" index:0])
        {
            self.AvgResolveL3 = [[[KPUHelper getNode:__node name:@"AvgResolveL3" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ScreenName" index:0])
        {
            self.ScreenName = [[KPUHelper getNode:__node name:@"ScreenName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ISPName" index:0])
        {
            self.ISPName = [[KPUHelper getNode:__node name:@"ISPName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IPAddress" index:0])
        {
            self.IPAddress = [[KPUHelper getNode:__node name:@"IPAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferenceName" index:0])
        {
            self.ReferenceName = [[KPUHelper getNode:__node name:@"ReferenceName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferencePhoneNumber" index:0])
        {
            self.ReferencePhoneNumber = [[KPUHelper getNode:__node name:@"ReferencePhoneNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferenceEmailAddress" index:0])
        {
            self.ReferenceEmailAddress = [[KPUHelper getNode:__node name:@"ReferenceEmailAddress" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKCurrencyID" index:0])
        {
            self.FKCurrencyID = [[[KPUHelper getNode:__node name:@"FKCurrencyID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"MonthlyPoints" index:0])
        {
            self.MonthlyPoints = [[KPUHelper getNode:__node name:@"MonthlyPoints" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"YearlyPoints" index:0])
        {
            self.YearlyPoints = [[KPUHelper getNode:__node name:@"YearlyPoints" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LastPaid" index:0])
        {
            self.LastPaid = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastPaid" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CurrencySymbol" index:0])
        {
            self.CurrencySymbol = [[KPUHelper getNode:__node name:@"CurrencySymbol" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Amount" index:0])
        {
            self.Amount = [[KPUHelper getNode:__node name:@"Amount" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKCountryID" index:0])
        {
            self.FKCountryID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKCountryID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"IsSkills" index:0])
        {
            self.IsSkills = [[[KPUHelper getNode:__node name:@"IsSkills" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"PreferedInterviewTime" index:0])
        {
            self.PreferedInterviewTime = [[KPUHelper getNode:__node name:@"PreferedInterviewTime" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"AlternativeTelephoneNumber" index:0])
        {
            self.AlternativeTelephoneNumber = [[KPUHelper getNode:__node name:@"AlternativeTelephoneNumber" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKResellerID" index:0])
        {
            self.FKResellerID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKResellerID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKEMPEngineerID" index:0])
        {
            self.FKEMPEngineerID = [[[KPUHelper getNode:__node name:@"FKEMPEngineerID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FKSecurityRoleId" index:0])
        {
            self.FKSecurityRoleId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKSecurityRoleId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKMenuId" index:0])
        {
            self.FKMenuId = [[[KPUHelper getNode:__node name:@"FKMenuId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ReferenceCode" index:0])
        {
            self.ReferenceCode = [[KPUHelper getNode:__node name:@"ReferenceCode" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"isLogged" index:0])
        {
            self.isLogged = [[[KPUHelper getNode:__node name:@"isLogged" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"CountryName" index:0])
        {
            self.CountryName = [[KPUHelper getNode:__node name:@"CountryName" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __DataStatItemElement=[__request writeElement:DataStat type:[KPUDataStatInfo class] name:@"DataStat" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DataStatItemElement!=nil)
    {
        [self.DataStat serialize:__DataStatItemElement __request: __request];
    }
             
    DDXMLElement* __CredentialItemElement=[__request writeElement:Credential type:[KPUCredentialInfo class] name:@"Credential" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CredentialItemElement!=nil)
    {
        [self.Credential serialize:__CredentialItemElement __request: __request];
    }
             
    DDXMLElement* __DepartmentIdItemElement=[__request writeElement:@"DepartmentId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__DepartmentIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.DepartmentId]];
             
    DDXMLElement* __UpdateEngineerItemElement=[__request writeElement:UpdateEngineer type:[KPUEngineerUpdateInfo class] name:@"UpdateEngineer" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UpdateEngineerItemElement!=nil)
    {
        [self.UpdateEngineer serialize:__UpdateEngineerItemElement __request: __request];
    }
             
    DDXMLElement* __PKEngineerIDItemElement=[__request writeElement:PKEngineerID type:[NSNumber class] name:@"PKEngineerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKEngineerIDItemElement!=nil)
    {
        [__PKEngineerIDItemElement setStringValue:[self.PKEngineerID stringValue]];
    }
             
    DDXMLElement* __RatingItemElement=[__request writeElement:Rating type:[NSNumber class] name:@"Rating" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__RatingItemElement!=nil)
    {
        [__RatingItemElement setStringValue:[self.Rating stringValue]];
    }
             
    DDXMLElement* __PhotoItemElement=[__request writeElement:Photo type:[NSString class] name:@"Photo" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PhotoItemElement!=nil)
    {
        [__PhotoItemElement setStringValue:self.Photo];
    }
             
    DDXMLElement* __FKRecordStatIDItemElement=[__request writeElement:FKRecordStatID type:[NSNumber class] name:@"FKRecordStatID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKRecordStatIDItemElement!=nil)
    {
        [__FKRecordStatIDItemElement setStringValue:[self.FKRecordStatID stringValue]];
    }
             
    DDXMLElement* __FKCredentialIDItemElement=[__request writeElement:FKCredentialID type:[NSNumber class] name:@"FKCredentialID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKCredentialIDItemElement!=nil)
    {
        [__FKCredentialIDItemElement setStringValue:[self.FKCredentialID stringValue]];
    }
             
    DDXMLElement* __FirstNameItemElement=[__request writeElement:FirstName type:[NSString class] name:@"FirstName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__FirstNameItemElement!=nil)
    {
        [__FirstNameItemElement setStringValue:self.FirstName];
    }
             
    DDXMLElement* __MiddleNameItemElement=[__request writeElement:MiddleName type:[NSString class] name:@"MiddleName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__MiddleNameItemElement!=nil)
    {
        [__MiddleNameItemElement setStringValue:self.MiddleName];
    }
             
    DDXMLElement* __LastNameItemElement=[__request writeElement:LastName type:[NSString class] name:@"LastName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LastNameItemElement!=nil)
    {
        [__LastNameItemElement setStringValue:self.LastName];
    }
             
    DDXMLElement* __AgentPINItemElement=[__request writeElement:AgentPIN type:[NSString class] name:@"AgentPIN" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__AgentPINItemElement!=nil)
    {
        [__AgentPINItemElement setStringValue:self.AgentPIN];
    }
             
    DDXMLElement* __AgentTypeItemElement=[__request writeElement:AgentType type:[NSNumber class] name:@"AgentType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__AgentTypeItemElement!=nil)
    {
        [__AgentTypeItemElement setStringValue:[self.AgentType stringValue]];
    }
             
    DDXMLElement* __LastIPAddressItemElement=[__request writeElement:LastIPAddress type:[NSString class] name:@"LastIPAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LastIPAddressItemElement!=nil)
    {
        [__LastIPAddressItemElement setStringValue:self.LastIPAddress];
    }
             
    DDXMLElement* __CreatedDatetimeItemElement=[__request writeElement:CreatedDatetime type:[NSDate class] name:@"CreatedDatetime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CreatedDatetimeItemElement!=nil)
    {
        [__CreatedDatetimeItemElement setStringValue:[KPUHelper getStringFromDate:self.CreatedDatetime]];
    }
             
    DDXMLElement* __LastLoginTImeItemElement=[__request writeElement:LastLoginTIme type:[NSDate class] name:@"LastLoginTIme" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastLoginTImeItemElement!=nil)
    {
        [__LastLoginTImeItemElement setStringValue:[KPUHelper getStringFromDate:self.LastLoginTIme]];
    }
             
    DDXMLElement* __UserNameItemElement=[__request writeElement:UserName type:[NSString class] name:@"UserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserNameItemElement!=nil)
    {
        [__UserNameItemElement setStringValue:self.UserName];
    }
             
    DDXMLElement* __ISActiveItemElement=[__request writeElement:@"ISActive" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ISActiveItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.ISActive]];
             
    DDXMLElement* __RealNameItemElement=[__request writeElement:RealName type:[NSString class] name:@"RealName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__RealNameItemElement!=nil)
    {
        [__RealNameItemElement setStringValue:self.RealName];
    }
             
    DDXMLElement* __isUpdateEmailItemElement=[__request writeElement:@"isUpdateEmail" URI:@"http://www.apoyar.net/" parent:__parent];
    [__isUpdateEmailItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.isUpdateEmail]];
             
    DDXMLElement* __CreateUserItemElement=[__request writeElement:CreateUser type:[NSString class] name:@"CreateUser" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CreateUserItemElement!=nil)
    {
        [__CreateUserItemElement setStringValue:self.CreateUser];
    }
             
    DDXMLElement* __UpdateUserItemElement=[__request writeElement:UpdateUser type:[NSString class] name:@"UpdateUser" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UpdateUserItemElement!=nil)
    {
        [__UpdateUserItemElement setStringValue:self.UpdateUser];
    }
             
    DDXMLElement* __UpdatedDateTimeItemElement=[__request writeElement:UpdatedDateTime type:[NSDate class] name:@"UpdatedDateTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UpdatedDateTimeItemElement!=nil)
    {
        [__UpdatedDateTimeItemElement setStringValue:[KPUHelper getStringFromDate:self.UpdatedDateTime]];
    }
             
    DDXMLElement* __SupportLanguageItemElement=[__request writeElement:SupportLanguage type:[NSString class] name:@"SupportLanguage" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__SupportLanguageItemElement!=nil)
    {
        [__SupportLanguageItemElement setStringValue:self.SupportLanguage];
    }
             
    DDXMLElement* __SecurityRoleNameItemElement=[__request writeElement:SecurityRoleName type:[NSString class] name:@"SecurityRoleName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__SecurityRoleNameItemElement!=nil)
    {
        [__SecurityRoleNameItemElement setStringValue:self.SecurityRoleName];
    }
             
    DDXMLElement* __TicketsCountItemElement=[__request writeElement:@"TicketsCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__TicketsCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.TicketsCount]];
             
    DDXMLElement* __UserRatingItemElement=[__request writeElement:UserRating type:[NSNumber class] name:@"UserRating" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__UserRatingItemElement!=nil)
    {
        [__UserRatingItemElement setStringValue:[self.UserRating stringValue]];
    }
             
    DDXMLElement* __FKLanguage1IDItemElement=[__request writeElement:FKLanguage1ID type:[NSNumber class] name:@"FKLanguage1ID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKLanguage1IDItemElement!=nil)
    {
        [__FKLanguage1IDItemElement setStringValue:[self.FKLanguage1ID stringValue]];
    }
             
    DDXMLElement* __FKLanguage2IDItemElement=[__request writeElement:FKLanguage2ID type:[NSNumber class] name:@"FKLanguage2ID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKLanguage2IDItemElement!=nil)
    {
        [__FKLanguage2IDItemElement setStringValue:[self.FKLanguage2ID stringValue]];
    }
             
    DDXMLElement* __FKLanguage3IDItemElement=[__request writeElement:FKLanguage3ID type:[NSNumber class] name:@"FKLanguage3ID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKLanguage3IDItemElement!=nil)
    {
        [__FKLanguage3IDItemElement setStringValue:[self.FKLanguage3ID stringValue]];
    }
             
    DDXMLElement* __FKLanguage4IDItemElement=[__request writeElement:FKLanguage4ID type:[NSNumber class] name:@"FKLanguage4ID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKLanguage4IDItemElement!=nil)
    {
        [__FKLanguage4IDItemElement setStringValue:[self.FKLanguage4ID stringValue]];
    }
             
    DDXMLElement* __ReceivedPassportItemElement=[__request writeElement:@"ReceivedPassport" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ReceivedPassportItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.ReceivedPassport]];
             
    DDXMLElement* __ReceivedScannedDocumentItemElement=[__request writeElement:@"ReceivedScannedDocument" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ReceivedScannedDocumentItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.ReceivedScannedDocument]];
             
    DDXMLElement* __VerifiedHomeAddressItemElement=[__request writeElement:@"VerifiedHomeAddress" URI:@"http://www.apoyar.net/" parent:__parent];
    [__VerifiedHomeAddressItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.VerifiedHomeAddress]];
             
    DDXMLElement* __CVItemElement=[__request writeElement:@"CV" URI:@"http://www.apoyar.net/" parent:__parent];
    [__CVItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.CV]];
             
    DDXMLElement* __VerifiedByItemElement=[__request writeElement:VerifiedBy type:[NSNumber class] name:@"VerifiedBy" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__VerifiedByItemElement!=nil)
    {
        [__VerifiedByItemElement setStringValue:[self.VerifiedBy stringValue]];
    }
             
    DDXMLElement* __VerifiedByTypeItemElement=[__request writeElement:@"VerifiedByType" URI:@"http://www.apoyar.net/" parent:__parent];
    [__VerifiedByTypeItemElement setStringValue: [NSString stringWithFormat:@"%i", self.VerifiedByType]];
             
    DDXMLElement* __VerifiedDateItemElement=[__request writeElement:VerifiedDate type:[NSDate class] name:@"VerifiedDate" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__VerifiedDateItemElement!=nil)
    {
        [__VerifiedDateItemElement setStringValue:[KPUHelper getStringFromDate:self.VerifiedDate]];
    }
             
    DDXMLElement* __InterviewDate1ItemElement=[__request writeElement:InterviewDate1 type:[NSDate class] name:@"InterviewDate1" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__InterviewDate1ItemElement!=nil)
    {
        [__InterviewDate1ItemElement setStringValue:[KPUHelper getStringFromDate:self.InterviewDate1]];
    }
             
    DDXMLElement* __InterviewPerson1ItemElement=[__request writeElement:InterviewPerson1 type:[NSNumber class] name:@"InterviewPerson1" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__InterviewPerson1ItemElement!=nil)
    {
        [__InterviewPerson1ItemElement setStringValue:[self.InterviewPerson1 stringValue]];
    }
             
    DDXMLElement* __InterviewPersonType1ItemElement=[__request writeElement:@"InterviewPersonType1" URI:@"http://www.apoyar.net/" parent:__parent];
    [__InterviewPersonType1ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.InterviewPersonType1]];
             
    DDXMLElement* __InterviewPersonResult1ItemElement=[__request writeElement:@"InterviewPersonResult1" URI:@"http://www.apoyar.net/" parent:__parent];
    [__InterviewPersonResult1ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.InterviewPersonResult1]];
             
    DDXMLElement* __InterviewDate2ItemElement=[__request writeElement:InterviewDate2 type:[NSDate class] name:@"InterviewDate2" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__InterviewDate2ItemElement!=nil)
    {
        [__InterviewDate2ItemElement setStringValue:[KPUHelper getStringFromDate:self.InterviewDate2]];
    }
             
    DDXMLElement* __InterviewPerson2ItemElement=[__request writeElement:InterviewPerson2 type:[NSNumber class] name:@"InterviewPerson2" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__InterviewPerson2ItemElement!=nil)
    {
        [__InterviewPerson2ItemElement setStringValue:[self.InterviewPerson2 stringValue]];
    }
             
    DDXMLElement* __InterviewPersonType2ItemElement=[__request writeElement:@"InterviewPersonType2" URI:@"http://www.apoyar.net/" parent:__parent];
    [__InterviewPersonType2ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.InterviewPersonType2]];
             
    DDXMLElement* __InterviewPersonResult2ItemElement=[__request writeElement:@"InterviewPersonResult2" URI:@"http://www.apoyar.net/" parent:__parent];
    [__InterviewPersonResult2ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.InterviewPersonResult2]];
             
    DDXMLElement* __ActivationStatusItemElement=[__request writeElement:@"ActivationStatus" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ActivationStatusItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ActivationStatus]];
             
    DDXMLElement* __AvgResolutionL1ItemElement=[__request writeElement:@"AvgResolutionL1" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolutionL1ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolutionL1]];
             
    DDXMLElement* __AvgResolutionL2ItemElement=[__request writeElement:@"AvgResolutionL2" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolutionL2ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolutionL2]];
             
    DDXMLElement* __AvgResolutionL3ItemElement=[__request writeElement:@"AvgResolutionL3" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolutionL3ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolutionL3]];
             
    DDXMLElement* __AvgResolveL1ItemElement=[__request writeElement:@"AvgResolveL1" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolveL1ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolveL1]];
             
    DDXMLElement* __AvgResolveL2ItemElement=[__request writeElement:@"AvgResolveL2" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolveL2ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolveL2]];
             
    DDXMLElement* __AvgResolveL3ItemElement=[__request writeElement:@"AvgResolveL3" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AvgResolveL3ItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AvgResolveL3]];
             
    DDXMLElement* __ScreenNameItemElement=[__request writeElement:ScreenName type:[NSString class] name:@"ScreenName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ScreenNameItemElement!=nil)
    {
        [__ScreenNameItemElement setStringValue:self.ScreenName];
    }
             
    DDXMLElement* __ISPNameItemElement=[__request writeElement:ISPName type:[NSString class] name:@"ISPName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ISPNameItemElement!=nil)
    {
        [__ISPNameItemElement setStringValue:self.ISPName];
    }
             
    DDXMLElement* __IPAddressItemElement=[__request writeElement:IPAddress type:[NSString class] name:@"IPAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__IPAddressItemElement!=nil)
    {
        [__IPAddressItemElement setStringValue:self.IPAddress];
    }
             
    DDXMLElement* __ReferenceNameItemElement=[__request writeElement:ReferenceName type:[NSString class] name:@"ReferenceName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ReferenceNameItemElement!=nil)
    {
        [__ReferenceNameItemElement setStringValue:self.ReferenceName];
    }
             
    DDXMLElement* __ReferencePhoneNumberItemElement=[__request writeElement:ReferencePhoneNumber type:[NSString class] name:@"ReferencePhoneNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ReferencePhoneNumberItemElement!=nil)
    {
        [__ReferencePhoneNumberItemElement setStringValue:self.ReferencePhoneNumber];
    }
             
    DDXMLElement* __ReferenceEmailAddressItemElement=[__request writeElement:ReferenceEmailAddress type:[NSString class] name:@"ReferenceEmailAddress" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ReferenceEmailAddressItemElement!=nil)
    {
        [__ReferenceEmailAddressItemElement setStringValue:self.ReferenceEmailAddress];
    }
             
    DDXMLElement* __FKCurrencyIDItemElement=[__request writeElement:@"FKCurrencyID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKCurrencyIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKCurrencyID]];
             
    DDXMLElement* __MonthlyPointsItemElement=[__request writeElement:MonthlyPoints type:[NSString class] name:@"MonthlyPoints" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__MonthlyPointsItemElement!=nil)
    {
        [__MonthlyPointsItemElement setStringValue:self.MonthlyPoints];
    }
             
    DDXMLElement* __YearlyPointsItemElement=[__request writeElement:YearlyPoints type:[NSString class] name:@"YearlyPoints" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__YearlyPointsItemElement!=nil)
    {
        [__YearlyPointsItemElement setStringValue:self.YearlyPoints];
    }
             
    DDXMLElement* __LastPaidItemElement=[__request writeElement:LastPaid type:[NSDate class] name:@"LastPaid" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastPaidItemElement!=nil)
    {
        [__LastPaidItemElement setStringValue:[KPUHelper getStringFromDate:self.LastPaid]];
    }
             
    DDXMLElement* __CurrencySymbolItemElement=[__request writeElement:CurrencySymbol type:[NSString class] name:@"CurrencySymbol" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CurrencySymbolItemElement!=nil)
    {
        [__CurrencySymbolItemElement setStringValue:self.CurrencySymbol];
    }
             
    DDXMLElement* __AmountItemElement=[__request writeElement:Amount type:[NSString class] name:@"Amount" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__AmountItemElement!=nil)
    {
        [__AmountItemElement setStringValue:self.Amount];
    }
             
    DDXMLElement* __FKCountryIDItemElement=[__request writeElement:FKCountryID type:[NSNumber class] name:@"FKCountryID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKCountryIDItemElement!=nil)
    {
        [__FKCountryIDItemElement setStringValue:[self.FKCountryID stringValue]];
    }
             
    DDXMLElement* __IsSkillsItemElement=[__request writeElement:@"IsSkills" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsSkillsItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsSkills]];
             
    DDXMLElement* __PreferedInterviewTimeItemElement=[__request writeElement:PreferedInterviewTime type:[NSString class] name:@"PreferedInterviewTime" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PreferedInterviewTimeItemElement!=nil)
    {
        [__PreferedInterviewTimeItemElement setStringValue:self.PreferedInterviewTime];
    }
             
    DDXMLElement* __AlternativeTelephoneNumberItemElement=[__request writeElement:AlternativeTelephoneNumber type:[NSString class] name:@"AlternativeTelephoneNumber" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__AlternativeTelephoneNumberItemElement!=nil)
    {
        [__AlternativeTelephoneNumberItemElement setStringValue:self.AlternativeTelephoneNumber];
    }
             
    DDXMLElement* __FKResellerIDItemElement=[__request writeElement:FKResellerID type:[NSNumber class] name:@"FKResellerID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKResellerIDItemElement!=nil)
    {
        [__FKResellerIDItemElement setStringValue:[self.FKResellerID stringValue]];
    }
             
    DDXMLElement* __FKEMPEngineerIDItemElement=[__request writeElement:@"FKEMPEngineerID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKEMPEngineerIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKEMPEngineerID]];
             
    DDXMLElement* __FKSecurityRoleIdItemElement=[__request writeElement:FKSecurityRoleId type:[NSNumber class] name:@"FKSecurityRoleId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKSecurityRoleIdItemElement!=nil)
    {
        [__FKSecurityRoleIdItemElement setStringValue:[self.FKSecurityRoleId stringValue]];
    }
             
    DDXMLElement* __FKMenuIdItemElement=[__request writeElement:@"FKMenuId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKMenuIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKMenuId]];
             
    DDXMLElement* __ReferenceCodeItemElement=[__request writeElement:ReferenceCode type:[NSString class] name:@"ReferenceCode" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ReferenceCodeItemElement!=nil)
    {
        [__ReferenceCodeItemElement setStringValue:self.ReferenceCode];
    }
             
    DDXMLElement* __isLoggedItemElement=[__request writeElement:@"isLogged" URI:@"http://www.apoyar.net/" parent:__parent];
    [__isLoggedItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.isLogged]];
             
    DDXMLElement* __CountryNameItemElement=[__request writeElement:CountryName type:[NSString class] name:@"CountryName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CountryNameItemElement!=nil)
    {
        [__CountryNameItemElement setStringValue:self.CountryName];
    }


}
@end
