//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUGetOverDueResponse : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getHoursofservice) NSString* hoursofservice;

@property (retain,nonatomic,getter=getResandconvvalue) NSNumber* resandconvvalue;

@property (retain,nonatomic,getter=getCurrdate) NSDate* currdate;

@property (retain,nonatomic,getter=getOverdue) NSString* overdue;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUGetOverDueResponse*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end