//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUPSAInfo.h"


@implementation KPUPSAInfo
@synthesize PSAID;
@synthesize FKServiceId;
@synthesize Email;
@synthesize Chat;
@synthesize Connect;
@synthesize CallMe;
@synthesize Visit;
@synthesize MyAccount;
@synthesize LastUpdated;
@synthesize Phone;
@synthesize YearlyFees;
@synthesize YearlyIncidents;
@synthesize HalfYearlyFees;
@synthesize HalfYearlyIncidents;
@synthesize QuarterlyFees;
@synthesize QuarterlyIncidents;
@synthesize MonthlyFees;
@synthesize MonthlyIncidents;
@synthesize OneIncidentFees;
@synthesize YearlyDescription;
@synthesize QuarterlyDescription;
@synthesize HalfYearlyDescription;
@synthesize MonthlyDescription;
@synthesize OneIncidentDescription;
@synthesize Term;
@synthesize Points;
@synthesize BonusPoints;
@synthesize SubscriptionValidity;
@synthesize SubscriptionBalance;
@synthesize PayAsYouGoValidity;
@synthesize PayAsYouGoBalance;
@synthesize PKAssetID;

+ (KPUPSAInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PSAID =[NSNumber numberWithInt:0];
        self.FKServiceId =[NSNumber numberWithInt:0];
        self.Email =[NSNumber numberWithInt:0];
        self.Chat =[NSNumber numberWithInt:0];
        self.Connect =[NSNumber numberWithInt:0];
        self.CallMe =[NSNumber numberWithInt:0];
        self.Visit =[NSNumber numberWithInt:0];
        self.MyAccount =[NSNumber numberWithInt:0];
        self.YearlyFees =[NSNumber numberWithInt:0];
        self.YearlyIncidents =[NSNumber numberWithInt:0];
        self.HalfYearlyFees =[NSNumber numberWithInt:0];
        self.HalfYearlyIncidents =[NSNumber numberWithInt:0];
        self.QuarterlyFees =[NSNumber numberWithInt:0];
        self.QuarterlyIncidents =[NSNumber numberWithInt:0];
        self.MonthlyFees =[NSNumber numberWithInt:0];
        self.MonthlyIncidents =[NSNumber numberWithInt:0];
        self.OneIncidentFees =[NSNumber numberWithInt:0];
        self.Points =0;
        self.BonusPoints =0;
        self.SubscriptionBalance =[NSNumber numberWithInt:0];
        self.PayAsYouGoBalance =[NSNumber numberWithInt:0];
        self.PKAssetID =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PSAID" index:0])
        {
            self.PSAID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PSAID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKServiceId" index:0])
        {
            self.FKServiceId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKServiceId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Email" index:0])
        {
            self.Email = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Email" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Chat" index:0])
        {
            self.Chat = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Chat" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Connect" index:0])
        {
            self.Connect = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Connect" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"CallMe" index:0])
        {
            self.CallMe = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"CallMe" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Visit" index:0])
        {
            self.Visit = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"Visit" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"MyAccount" index:0])
        {
            self.MyAccount = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"MyAccount" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"LastUpdated" index:0])
        {
            self.LastUpdated = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"LastUpdated" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"Phone" index:0])
        {
            self.Phone = [[KPUHelper getNode:__node name:@"Phone" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"YearlyFees" index:0])
        {
            self.YearlyFees = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"YearlyFees" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"YearlyIncidents" index:0])
        {
            self.YearlyIncidents = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"YearlyIncidents" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"HalfYearlyFees" index:0])
        {
            self.HalfYearlyFees = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"HalfYearlyFees" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"HalfYearlyIncidents" index:0])
        {
            self.HalfYearlyIncidents = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"HalfYearlyIncidents" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"QuarterlyFees" index:0])
        {
            self.QuarterlyFees = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"QuarterlyFees" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"QuarterlyIncidents" index:0])
        {
            self.QuarterlyIncidents = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"QuarterlyIncidents" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"MonthlyFees" index:0])
        {
            self.MonthlyFees = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"MonthlyFees" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"MonthlyIncidents" index:0])
        {
            self.MonthlyIncidents = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"MonthlyIncidents" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"OneIncidentFees" index:0])
        {
            self.OneIncidentFees = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"OneIncidentFees" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"YearlyDescription" index:0])
        {
            self.YearlyDescription = [[KPUHelper getNode:__node name:@"YearlyDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"QuarterlyDescription" index:0])
        {
            self.QuarterlyDescription = [[KPUHelper getNode:__node name:@"QuarterlyDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"HalfYearlyDescription" index:0])
        {
            self.HalfYearlyDescription = [[KPUHelper getNode:__node name:@"HalfYearlyDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"MonthlyDescription" index:0])
        {
            self.MonthlyDescription = [[KPUHelper getNode:__node name:@"MonthlyDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"OneIncidentDescription" index:0])
        {
            self.OneIncidentDescription = [[KPUHelper getNode:__node name:@"OneIncidentDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Term" index:0])
        {
            self.Term = [[KPUHelper getNode:__node name:@"Term" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Points" index:0])
        {
            self.Points = [[[KPUHelper getNode:__node name:@"Points" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"BonusPoints" index:0])
        {
            self.BonusPoints = [[[KPUHelper getNode:__node name:@"BonusPoints" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"SubscriptionValidity" index:0])
        {
            self.SubscriptionValidity = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"SubscriptionValidity" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"SubscriptionBalance" index:0])
        {
            self.SubscriptionBalance = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"SubscriptionBalance" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PayAsYouGoValidity" index:0])
        {
            self.PayAsYouGoValidity = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"PayAsYouGoValidity" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PayAsYouGoBalance" index:0])
        {
            self.PayAsYouGoBalance = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PayAsYouGoBalance" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"PKAssetID" index:0])
        {
            self.PKAssetID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKAssetID" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PSAIDItemElement=[__request writeElement:PSAID type:[NSNumber class] name:@"PSAID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PSAIDItemElement!=nil)
    {
        [__PSAIDItemElement setStringValue:[self.PSAID stringValue]];
    }
             
    DDXMLElement* __FKServiceIdItemElement=[__request writeElement:FKServiceId type:[NSNumber class] name:@"FKServiceId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKServiceIdItemElement!=nil)
    {
        [__FKServiceIdItemElement setStringValue:[self.FKServiceId stringValue]];
    }
             
    DDXMLElement* __EmailItemElement=[__request writeElement:Email type:[NSNumber class] name:@"Email" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__EmailItemElement!=nil)
    {
        [__EmailItemElement setStringValue:[self.Email stringValue]];
    }
             
    DDXMLElement* __ChatItemElement=[__request writeElement:Chat type:[NSNumber class] name:@"Chat" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ChatItemElement!=nil)
    {
        [__ChatItemElement setStringValue:[self.Chat stringValue]];
    }
             
    DDXMLElement* __ConnectItemElement=[__request writeElement:Connect type:[NSNumber class] name:@"Connect" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ConnectItemElement!=nil)
    {
        [__ConnectItemElement setStringValue:[self.Connect stringValue]];
    }
             
    DDXMLElement* __CallMeItemElement=[__request writeElement:CallMe type:[NSNumber class] name:@"CallMe" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__CallMeItemElement!=nil)
    {
        [__CallMeItemElement setStringValue:[self.CallMe stringValue]];
    }
             
    DDXMLElement* __VisitItemElement=[__request writeElement:Visit type:[NSNumber class] name:@"Visit" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__VisitItemElement!=nil)
    {
        [__VisitItemElement setStringValue:[self.Visit stringValue]];
    }
             
    DDXMLElement* __MyAccountItemElement=[__request writeElement:MyAccount type:[NSNumber class] name:@"MyAccount" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__MyAccountItemElement!=nil)
    {
        [__MyAccountItemElement setStringValue:[self.MyAccount stringValue]];
    }
             
    DDXMLElement* __LastUpdatedItemElement=[__request writeElement:LastUpdated type:[NSDate class] name:@"LastUpdated" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__LastUpdatedItemElement!=nil)
    {
        [__LastUpdatedItemElement setStringValue:[KPUHelper getStringFromDate:self.LastUpdated]];
    }
             
    DDXMLElement* __PhoneItemElement=[__request writeElement:Phone type:[NSString class] name:@"Phone" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PhoneItemElement!=nil)
    {
        [__PhoneItemElement setStringValue:self.Phone];
    }
             
    DDXMLElement* __YearlyFeesItemElement=[__request writeElement:YearlyFees type:[NSNumber class] name:@"YearlyFees" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__YearlyFeesItemElement!=nil)
    {
        [__YearlyFeesItemElement setStringValue:[self.YearlyFees stringValue]];
    }
             
    DDXMLElement* __YearlyIncidentsItemElement=[__request writeElement:YearlyIncidents type:[NSNumber class] name:@"YearlyIncidents" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__YearlyIncidentsItemElement!=nil)
    {
        [__YearlyIncidentsItemElement setStringValue:[self.YearlyIncidents stringValue]];
    }
             
    DDXMLElement* __HalfYearlyFeesItemElement=[__request writeElement:HalfYearlyFees type:[NSNumber class] name:@"HalfYearlyFees" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__HalfYearlyFeesItemElement!=nil)
    {
        [__HalfYearlyFeesItemElement setStringValue:[self.HalfYearlyFees stringValue]];
    }
             
    DDXMLElement* __HalfYearlyIncidentsItemElement=[__request writeElement:HalfYearlyIncidents type:[NSNumber class] name:@"HalfYearlyIncidents" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__HalfYearlyIncidentsItemElement!=nil)
    {
        [__HalfYearlyIncidentsItemElement setStringValue:[self.HalfYearlyIncidents stringValue]];
    }
             
    DDXMLElement* __QuarterlyFeesItemElement=[__request writeElement:QuarterlyFees type:[NSNumber class] name:@"QuarterlyFees" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__QuarterlyFeesItemElement!=nil)
    {
        [__QuarterlyFeesItemElement setStringValue:[self.QuarterlyFees stringValue]];
    }
             
    DDXMLElement* __QuarterlyIncidentsItemElement=[__request writeElement:QuarterlyIncidents type:[NSNumber class] name:@"QuarterlyIncidents" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__QuarterlyIncidentsItemElement!=nil)
    {
        [__QuarterlyIncidentsItemElement setStringValue:[self.QuarterlyIncidents stringValue]];
    }
             
    DDXMLElement* __MonthlyFeesItemElement=[__request writeElement:MonthlyFees type:[NSNumber class] name:@"MonthlyFees" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__MonthlyFeesItemElement!=nil)
    {
        [__MonthlyFeesItemElement setStringValue:[self.MonthlyFees stringValue]];
    }
             
    DDXMLElement* __MonthlyIncidentsItemElement=[__request writeElement:MonthlyIncidents type:[NSNumber class] name:@"MonthlyIncidents" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__MonthlyIncidentsItemElement!=nil)
    {
        [__MonthlyIncidentsItemElement setStringValue:[self.MonthlyIncidents stringValue]];
    }
             
    DDXMLElement* __OneIncidentFeesItemElement=[__request writeElement:OneIncidentFees type:[NSNumber class] name:@"OneIncidentFees" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__OneIncidentFeesItemElement!=nil)
    {
        [__OneIncidentFeesItemElement setStringValue:[self.OneIncidentFees stringValue]];
    }
             
    DDXMLElement* __YearlyDescriptionItemElement=[__request writeElement:YearlyDescription type:[NSString class] name:@"YearlyDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__YearlyDescriptionItemElement!=nil)
    {
        [__YearlyDescriptionItemElement setStringValue:self.YearlyDescription];
    }
             
    DDXMLElement* __QuarterlyDescriptionItemElement=[__request writeElement:QuarterlyDescription type:[NSString class] name:@"QuarterlyDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__QuarterlyDescriptionItemElement!=nil)
    {
        [__QuarterlyDescriptionItemElement setStringValue:self.QuarterlyDescription];
    }
             
    DDXMLElement* __HalfYearlyDescriptionItemElement=[__request writeElement:HalfYearlyDescription type:[NSString class] name:@"HalfYearlyDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__HalfYearlyDescriptionItemElement!=nil)
    {
        [__HalfYearlyDescriptionItemElement setStringValue:self.HalfYearlyDescription];
    }
             
    DDXMLElement* __MonthlyDescriptionItemElement=[__request writeElement:MonthlyDescription type:[NSString class] name:@"MonthlyDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__MonthlyDescriptionItemElement!=nil)
    {
        [__MonthlyDescriptionItemElement setStringValue:self.MonthlyDescription];
    }
             
    DDXMLElement* __OneIncidentDescriptionItemElement=[__request writeElement:OneIncidentDescription type:[NSString class] name:@"OneIncidentDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__OneIncidentDescriptionItemElement!=nil)
    {
        [__OneIncidentDescriptionItemElement setStringValue:self.OneIncidentDescription];
    }
             
    DDXMLElement* __TermItemElement=[__request writeElement:Term type:[NSString class] name:@"Term" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TermItemElement!=nil)
    {
        [__TermItemElement setStringValue:self.Term];
    }
             
    DDXMLElement* __PointsItemElement=[__request writeElement:@"Points" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PointsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.Points]];
             
    DDXMLElement* __BonusPointsItemElement=[__request writeElement:@"BonusPoints" URI:@"http://www.apoyar.net/" parent:__parent];
    [__BonusPointsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.BonusPoints]];
             
    DDXMLElement* __SubscriptionValidityItemElement=[__request writeElement:SubscriptionValidity type:[NSDate class] name:@"SubscriptionValidity" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__SubscriptionValidityItemElement!=nil)
    {
        [__SubscriptionValidityItemElement setStringValue:[KPUHelper getStringFromDate:self.SubscriptionValidity]];
    }
             
    DDXMLElement* __SubscriptionBalanceItemElement=[__request writeElement:SubscriptionBalance type:[NSNumber class] name:@"SubscriptionBalance" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__SubscriptionBalanceItemElement!=nil)
    {
        [__SubscriptionBalanceItemElement setStringValue:[self.SubscriptionBalance stringValue]];
    }
             
    DDXMLElement* __PayAsYouGoValidityItemElement=[__request writeElement:PayAsYouGoValidity type:[NSDate class] name:@"PayAsYouGoValidity" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PayAsYouGoValidityItemElement!=nil)
    {
        [__PayAsYouGoValidityItemElement setStringValue:[KPUHelper getStringFromDate:self.PayAsYouGoValidity]];
    }
             
    DDXMLElement* __PayAsYouGoBalanceItemElement=[__request writeElement:PayAsYouGoBalance type:[NSNumber class] name:@"PayAsYouGoBalance" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PayAsYouGoBalanceItemElement!=nil)
    {
        [__PayAsYouGoBalanceItemElement setStringValue:[self.PayAsYouGoBalance stringValue]];
    }
             
    DDXMLElement* __PKAssetIDItemElement=[__request writeElement:PKAssetID type:[NSNumber class] name:@"PKAssetID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKAssetIDItemElement!=nil)
    {
        [__PKAssetIDItemElement setStringValue:[self.PKAssetID stringValue]];
    }


}
@end
