//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUPSAInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getPSAID) NSNumber* PSAID;

@property (retain,nonatomic,getter=getFKServiceId) NSNumber* FKServiceId;

@property (retain,nonatomic,getter=getEmail) NSNumber* Email;

@property (retain,nonatomic,getter=getChat) NSNumber* Chat;

@property (retain,nonatomic,getter=getConnect) NSNumber* Connect;

@property (retain,nonatomic,getter=getCallMe) NSNumber* CallMe;

@property (retain,nonatomic,getter=getVisit) NSNumber* Visit;

@property (retain,nonatomic,getter=getMyAccount) NSNumber* MyAccount;

@property (retain,nonatomic,getter=getLastUpdated) NSDate* LastUpdated;

@property (retain,nonatomic,getter=getPhone) NSString* Phone;

@property (retain,nonatomic,getter=getYearlyFees) NSNumber* YearlyFees;

@property (retain,nonatomic,getter=getYearlyIncidents) NSNumber* YearlyIncidents;

@property (retain,nonatomic,getter=getHalfYearlyFees) NSNumber* HalfYearlyFees;

@property (retain,nonatomic,getter=getHalfYearlyIncidents) NSNumber* HalfYearlyIncidents;

@property (retain,nonatomic,getter=getQuarterlyFees) NSNumber* QuarterlyFees;

@property (retain,nonatomic,getter=getQuarterlyIncidents) NSNumber* QuarterlyIncidents;

@property (retain,nonatomic,getter=getMonthlyFees) NSNumber* MonthlyFees;

@property (retain,nonatomic,getter=getMonthlyIncidents) NSNumber* MonthlyIncidents;

@property (retain,nonatomic,getter=getOneIncidentFees) NSNumber* OneIncidentFees;

@property (retain,nonatomic,getter=getYearlyDescription) NSString* YearlyDescription;

@property (retain,nonatomic,getter=getQuarterlyDescription) NSString* QuarterlyDescription;

@property (retain,nonatomic,getter=getHalfYearlyDescription) NSString* HalfYearlyDescription;

@property (retain,nonatomic,getter=getMonthlyDescription) NSString* MonthlyDescription;

@property (retain,nonatomic,getter=getOneIncidentDescription) NSString* OneIncidentDescription;

@property (retain,nonatomic,getter=getTerm) NSString* Term;

@property (nonatomic,getter=getPoints) int Points;

@property (nonatomic,getter=getBonusPoints) int BonusPoints;

@property (retain,nonatomic,getter=getSubscriptionValidity) NSDate* SubscriptionValidity;

@property (retain,nonatomic,getter=getSubscriptionBalance) NSNumber* SubscriptionBalance;

@property (retain,nonatomic,getter=getPayAsYouGoValidity) NSDate* PayAsYouGoValidity;

@property (retain,nonatomic,getter=getPayAsYouGoBalance) NSNumber* PayAsYouGoBalance;

@property (retain,nonatomic,getter=getPKAssetID) NSNumber* PKAssetID;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUPSAInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end