//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUSLAInfo;
@class KPUContractInfo;
@class KPUHoursOfServiceInfo;
@class KPUPSAInfo;
@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUServiceInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getSLA) KPUSLAInfo* SLA;

@property (retain,nonatomic,getter=getContract) KPUContractInfo* Contract;

@property (retain,nonatomic,getter=getHoursOfService) KPUHoursOfServiceInfo* HoursOfService;

@property (retain,nonatomic,getter=getPSAService) KPUPSAInfo* PSAService;

@property (retain,nonatomic,getter=getPKServiceID) NSNumber* PKServiceID;

@property (retain,nonatomic,getter=getServiceName) NSString* ServiceName;

@property (retain,nonatomic,getter=getServiceType) NSNumber* ServiceType;

@property (nonatomic,getter=getContractCount) int ContractCount;

@property (nonatomic,getter=getHOSCount) int HOSCount;

@property (retain,nonatomic,getter=getResolutionSla) NSString* ResolutionSla;

@property (retain,nonatomic,getter=getResponseSLA) NSString* ResponseSLA;

@property (nonatomic,getter=getIsServiceCatalogue) BOOL IsServiceCatalogue;

@property (retain,nonatomic,getter=getEarnPointsMultiplier) NSNumber* EarnPointsMultiplier;

@property (retain,nonatomic,getter=getEngineerPointsMultiplier) NSNumber* EngineerPointsMultiplier;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUServiceInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end