//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUSLAInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getPKSLAId) NSNumber* PKSLAId;

@property (retain,nonatomic,getter=getFKServiceId) NSNumber* FKServiceId;

@property (retain,nonatomic,getter=getResponseThreshold) NSNumber* ResponseThreshold;

@property (retain,nonatomic,getter=getResolutionThreshold) NSNumber* ResolutionThreshold;

@property (retain,nonatomic,getter=getFKResponseUnitId) NSNumber* FKResponseUnitId;

@property (retain,nonatomic,getter=getFKResolutionUnitId) NSNumber* FKResolutionUnitId;

@property (retain,nonatomic,getter=getThresholdValue) NSNumber* ThresholdValue;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUSLAInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end