//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUSLAInfo.h"


@implementation KPUSLAInfo
@synthesize PKSLAId;
@synthesize FKServiceId;
@synthesize ResponseThreshold;
@synthesize ResolutionThreshold;
@synthesize FKResponseUnitId;
@synthesize FKResolutionUnitId;
@synthesize ThresholdValue;

+ (KPUSLAInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKSLAId =[NSNumber numberWithInt:0];
        self.FKServiceId =[NSNumber numberWithInt:0];
        self.ResponseThreshold =[NSNumber numberWithInt:0];
        self.ResolutionThreshold =[NSNumber numberWithInt:0];
        self.FKResponseUnitId =[NSNumber numberWithInt:0];
        self.FKResolutionUnitId =[NSNumber numberWithInt:0];
        self.ThresholdValue =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKSLAId" index:0])
        {
            self.PKSLAId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKSLAId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKServiceId" index:0])
        {
            self.FKServiceId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKServiceId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ResponseThreshold" index:0])
        {
            self.ResponseThreshold = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"ResponseThreshold" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ResolutionThreshold" index:0])
        {
            self.ResolutionThreshold = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"ResolutionThreshold" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKResponseUnitId" index:0])
        {
            self.FKResponseUnitId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKResponseUnitId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"FKResolutionUnitId" index:0])
        {
            self.FKResolutionUnitId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKResolutionUnitId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ThresholdValue" index:0])
        {
            self.ThresholdValue = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"ThresholdValue" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKSLAIdItemElement=[__request writeElement:PKSLAId type:[NSNumber class] name:@"PKSLAId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKSLAIdItemElement!=nil)
    {
        [__PKSLAIdItemElement setStringValue:[self.PKSLAId stringValue]];
    }
             
    DDXMLElement* __FKServiceIdItemElement=[__request writeElement:FKServiceId type:[NSNumber class] name:@"FKServiceId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKServiceIdItemElement!=nil)
    {
        [__FKServiceIdItemElement setStringValue:[self.FKServiceId stringValue]];
    }
             
    DDXMLElement* __ResponseThresholdItemElement=[__request writeElement:ResponseThreshold type:[NSNumber class] name:@"ResponseThreshold" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ResponseThresholdItemElement!=nil)
    {
        [__ResponseThresholdItemElement setStringValue:[self.ResponseThreshold stringValue]];
    }
             
    DDXMLElement* __ResolutionThresholdItemElement=[__request writeElement:ResolutionThreshold type:[NSNumber class] name:@"ResolutionThreshold" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ResolutionThresholdItemElement!=nil)
    {
        [__ResolutionThresholdItemElement setStringValue:[self.ResolutionThreshold stringValue]];
    }
             
    DDXMLElement* __FKResponseUnitIdItemElement=[__request writeElement:FKResponseUnitId type:[NSNumber class] name:@"FKResponseUnitId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKResponseUnitIdItemElement!=nil)
    {
        [__FKResponseUnitIdItemElement setStringValue:[self.FKResponseUnitId stringValue]];
    }
             
    DDXMLElement* __FKResolutionUnitIdItemElement=[__request writeElement:FKResolutionUnitId type:[NSNumber class] name:@"FKResolutionUnitId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKResolutionUnitIdItemElement!=nil)
    {
        [__FKResolutionUnitIdItemElement setStringValue:[self.FKResolutionUnitId stringValue]];
    }
             
    DDXMLElement* __ThresholdValueItemElement=[__request writeElement:ThresholdValue type:[NSNumber class] name:@"ThresholdValue" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ThresholdValueItemElement!=nil)
    {
        [__ThresholdValueItemElement setStringValue:[self.ThresholdValue stringValue]];
    }


}
@end
