//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUStructTicketDetailsForZeb.h"


@implementation KPUStructTicketDetailsForZeb
@synthesize PKTicketId;
@synthesize TicketTitle;
@synthesize TicketStatus;
@synthesize FKTicketStatusID;
@synthesize CustomerID;
@synthesize CustomerName;
@synthesize StoreName;
@synthesize StatusName;
@synthesize TicketSubStatusName;
@synthesize TicketCreated;
@synthesize ResolutionSLA;
@synthesize TicketDescription;
@synthesize TicketTypeName;
@synthesize AttachmentID;

+ (KPUStructTicketDetailsForZeb *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKTicketId =0;
        self.TicketStatus =0;
        self.FKTicketStatusID =0;
        self.CustomerID =0;
        self.AttachmentID =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKTicketId" index:0])
        {
            self.PKTicketId = [[[KPUHelper getNode:__node name:@"PKTicketId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketTitle" index:0])
        {
            self.TicketTitle = [[KPUHelper getNode:__node name:@"TicketTitle" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketStatus" index:0])
        {
            self.TicketStatus = [[[KPUHelper getNode:__node name:@"TicketStatus" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"FKTicketStatusID" index:0])
        {
            self.FKTicketStatusID = [[[KPUHelper getNode:__node name:@"FKTicketStatusID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"CustomerID" index:0])
        {
            self.CustomerID = [[[KPUHelper getNode:__node name:@"CustomerID" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"CustomerName" index:0])
        {
            self.CustomerName = [[KPUHelper getNode:__node name:@"CustomerName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"StoreName" index:0])
        {
            self.StoreName = [[KPUHelper getNode:__node name:@"StoreName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"StatusName" index:0])
        {
            self.StatusName = [[KPUHelper getNode:__node name:@"StatusName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketSubStatusName" index:0])
        {
            self.TicketSubStatusName = [[KPUHelper getNode:__node name:@"TicketSubStatusName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketCreated" index:0])
        {
            self.TicketCreated = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"TicketCreated" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ResolutionSLA" index:0])
        {
            self.ResolutionSLA = [KPUHelper getDate:[[KPUHelper getNode:__node name:@"ResolutionSLA" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"TicketDescription" index:0])
        {
            self.TicketDescription = [[KPUHelper getNode:__node name:@"TicketDescription" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"TicketTypeName" index:0])
        {
            self.TicketTypeName = [[KPUHelper getNode:__node name:@"TicketTypeName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"AttachmentID" index:0])
        {
            self.AttachmentID = [[[KPUHelper getNode:__node name:@"AttachmentID" index:0] stringValue] intValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKTicketIdItemElement=[__request writeElement:@"PKTicketId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__PKTicketIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.PKTicketId]];
             
    DDXMLElement* __TicketTitleItemElement=[__request writeElement:TicketTitle type:[NSString class] name:@"TicketTitle" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TicketTitleItemElement!=nil)
    {
        [__TicketTitleItemElement setStringValue:self.TicketTitle];
    }
             
    DDXMLElement* __TicketStatusItemElement=[__request writeElement:@"TicketStatus" URI:@"http://www.apoyar.net/" parent:__parent];
    [__TicketStatusItemElement setStringValue: [NSString stringWithFormat:@"%i", self.TicketStatus]];
             
    DDXMLElement* __FKTicketStatusIDItemElement=[__request writeElement:@"FKTicketStatusID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKTicketStatusIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKTicketStatusID]];
             
    DDXMLElement* __CustomerIDItemElement=[__request writeElement:@"CustomerID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__CustomerIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.CustomerID]];
             
    DDXMLElement* __CustomerNameItemElement=[__request writeElement:CustomerName type:[NSString class] name:@"CustomerName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__CustomerNameItemElement!=nil)
    {
        [__CustomerNameItemElement setStringValue:self.CustomerName];
    }
             
    DDXMLElement* __StoreNameItemElement=[__request writeElement:StoreName type:[NSString class] name:@"StoreName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__StoreNameItemElement!=nil)
    {
        [__StoreNameItemElement setStringValue:self.StoreName];
    }
             
    DDXMLElement* __StatusNameItemElement=[__request writeElement:StatusName type:[NSString class] name:@"StatusName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__StatusNameItemElement!=nil)
    {
        [__StatusNameItemElement setStringValue:self.StatusName];
    }
             
    DDXMLElement* __TicketSubStatusNameItemElement=[__request writeElement:TicketSubStatusName type:[NSString class] name:@"TicketSubStatusName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TicketSubStatusNameItemElement!=nil)
    {
        [__TicketSubStatusNameItemElement setStringValue:self.TicketSubStatusName];
    }
             
    DDXMLElement* __TicketCreatedItemElement=[__request writeElement:TicketCreated type:[NSDate class] name:@"TicketCreated" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__TicketCreatedItemElement!=nil)
    {
        [__TicketCreatedItemElement setStringValue:[KPUHelper getStringFromDate:self.TicketCreated]];
    }
             
    DDXMLElement* __ResolutionSLAItemElement=[__request writeElement:ResolutionSLA type:[NSDate class] name:@"ResolutionSLA" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ResolutionSLAItemElement!=nil)
    {
        [__ResolutionSLAItemElement setStringValue:[KPUHelper getStringFromDate:self.ResolutionSLA]];
    }
             
    DDXMLElement* __TicketDescriptionItemElement=[__request writeElement:TicketDescription type:[NSString class] name:@"TicketDescription" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TicketDescriptionItemElement!=nil)
    {
        [__TicketDescriptionItemElement setStringValue:self.TicketDescription];
    }
             
    DDXMLElement* __TicketTypeNameItemElement=[__request writeElement:TicketTypeName type:[NSString class] name:@"TicketTypeName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TicketTypeNameItemElement!=nil)
    {
        [__TicketTypeNameItemElement setStringValue:self.TicketTypeName];
    }
             
    DDXMLElement* __AttachmentIDItemElement=[__request writeElement:@"AttachmentID" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AttachmentIDItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AttachmentID]];


}
@end
