//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUSLAInfo.h"
#import "KPUContractInfo.h"
#import "KPUHoursOfServiceInfo.h"
#import "KPUPSAInfo.h"
#import "KPUHelper.h"
#import "KPUServiceInfo.h"


@implementation KPUServiceInfo
@synthesize SLA;
@synthesize Contract;
@synthesize HoursOfService;
@synthesize PSAService;
@synthesize PKServiceID;
@synthesize ServiceName;
@synthesize ServiceType;
@synthesize ContractCount;
@synthesize HOSCount;
@synthesize ResolutionSla;
@synthesize ResponseSLA;
@synthesize IsServiceCatalogue;
@synthesize EarnPointsMultiplier;
@synthesize EngineerPointsMultiplier;

+ (KPUServiceInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKServiceID =[NSNumber numberWithInt:0];
        self.ServiceType =[NSNumber numberWithInt:0];
        self.ContractCount =0;
        self.HOSCount =0;
        self.EarnPointsMultiplier =[NSNumber numberWithInt:0];
        self.EngineerPointsMultiplier =[NSNumber numberWithInt:0];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"SLA" index:0])
        {
            self.SLA = (KPUSLAInfo*)[__request createObject:[KPUHelper getNode:__node name:@"SLA" index:0] type:[KPUSLAInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"Contract" index:0])
        {
            self.Contract = (KPUContractInfo*)[__request createObject:[KPUHelper getNode:__node name:@"Contract" index:0] type:[KPUContractInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"HoursOfService" index:0])
        {
            self.HoursOfService = (KPUHoursOfServiceInfo*)[__request createObject:[KPUHelper getNode:__node name:@"HoursOfService" index:0] type:[KPUHoursOfServiceInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"PSAService" index:0])
        {
            self.PSAService = (KPUPSAInfo*)[__request createObject:[KPUHelper getNode:__node name:@"PSAService" index:0] type:[KPUPSAInfo class]];
        }
        if([KPUHelper hasValue:__node name:@"PKServiceID" index:0])
        {
            self.PKServiceID = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKServiceID" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ServiceName" index:0])
        {
            self.ServiceName = [[KPUHelper getNode:__node name:@"ServiceName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ServiceType" index:0])
        {
            self.ServiceType = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"ServiceType" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"ContractCount" index:0])
        {
            self.ContractCount = [[[KPUHelper getNode:__node name:@"ContractCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"HOSCount" index:0])
        {
            self.HOSCount = [[[KPUHelper getNode:__node name:@"HOSCount" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"ResolutionSla" index:0])
        {
            self.ResolutionSla = [[KPUHelper getNode:__node name:@"ResolutionSla" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"ResponseSLA" index:0])
        {
            self.ResponseSLA = [[KPUHelper getNode:__node name:@"ResponseSLA" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsServiceCatalogue" index:0])
        {
            self.IsServiceCatalogue = [[[KPUHelper getNode:__node name:@"IsServiceCatalogue" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"EarnPointsMultiplier" index:0])
        {
            self.EarnPointsMultiplier = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"EarnPointsMultiplier" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"EngineerPointsMultiplier" index:0])
        {
            self.EngineerPointsMultiplier = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"EngineerPointsMultiplier" index:0] stringValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __SLAItemElement=[__request writeElement:SLA type:[KPUSLAInfo class] name:@"SLA" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__SLAItemElement!=nil)
    {
        [self.SLA serialize:__SLAItemElement __request: __request];
    }
             
    DDXMLElement* __ContractItemElement=[__request writeElement:Contract type:[KPUContractInfo class] name:@"Contract" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ContractItemElement!=nil)
    {
        [self.Contract serialize:__ContractItemElement __request: __request];
    }
             
    DDXMLElement* __HoursOfServiceItemElement=[__request writeElement:HoursOfService type:[KPUHoursOfServiceInfo class] name:@"HoursOfService" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__HoursOfServiceItemElement!=nil)
    {
        [self.HoursOfService serialize:__HoursOfServiceItemElement __request: __request];
    }
             
    DDXMLElement* __PSAServiceItemElement=[__request writeElement:PSAService type:[KPUPSAInfo class] name:@"PSAService" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PSAServiceItemElement!=nil)
    {
        [self.PSAService serialize:__PSAServiceItemElement __request: __request];
    }
             
    DDXMLElement* __PKServiceIDItemElement=[__request writeElement:PKServiceID type:[NSNumber class] name:@"PKServiceID" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKServiceIDItemElement!=nil)
    {
        [__PKServiceIDItemElement setStringValue:[self.PKServiceID stringValue]];
    }
             
    DDXMLElement* __ServiceNameItemElement=[__request writeElement:ServiceName type:[NSString class] name:@"ServiceName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ServiceNameItemElement!=nil)
    {
        [__ServiceNameItemElement setStringValue:self.ServiceName];
    }
             
    DDXMLElement* __ServiceTypeItemElement=[__request writeElement:ServiceType type:[NSNumber class] name:@"ServiceType" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__ServiceTypeItemElement!=nil)
    {
        [__ServiceTypeItemElement setStringValue:[self.ServiceType stringValue]];
    }
             
    DDXMLElement* __ContractCountItemElement=[__request writeElement:@"ContractCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__ContractCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.ContractCount]];
             
    DDXMLElement* __HOSCountItemElement=[__request writeElement:@"HOSCount" URI:@"http://www.apoyar.net/" parent:__parent];
    [__HOSCountItemElement setStringValue: [NSString stringWithFormat:@"%i", self.HOSCount]];
             
    DDXMLElement* __ResolutionSlaItemElement=[__request writeElement:ResolutionSla type:[NSString class] name:@"ResolutionSla" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ResolutionSlaItemElement!=nil)
    {
        [__ResolutionSlaItemElement setStringValue:self.ResolutionSla];
    }
             
    DDXMLElement* __ResponseSLAItemElement=[__request writeElement:ResponseSLA type:[NSString class] name:@"ResponseSLA" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__ResponseSLAItemElement!=nil)
    {
        [__ResponseSLAItemElement setStringValue:self.ResponseSLA];
    }
             
    DDXMLElement* __IsServiceCatalogueItemElement=[__request writeElement:@"IsServiceCatalogue" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsServiceCatalogueItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsServiceCatalogue]];
             
    DDXMLElement* __EarnPointsMultiplierItemElement=[__request writeElement:EarnPointsMultiplier type:[NSNumber class] name:@"EarnPointsMultiplier" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__EarnPointsMultiplierItemElement!=nil)
    {
        [__EarnPointsMultiplierItemElement setStringValue:[self.EarnPointsMultiplier stringValue]];
    }
             
    DDXMLElement* __EngineerPointsMultiplierItemElement=[__request writeElement:EngineerPointsMultiplier type:[NSNumber class] name:@"EngineerPointsMultiplier" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__EngineerPointsMultiplierItemElement!=nil)
    {
        [__EngineerPointsMultiplierItemElement setStringValue:[self.EngineerPointsMultiplier stringValue]];
    }


}
@end
