//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
    
#import "KPUTicketUpdatedBy.h"

@implementation KPUTicketUpdatedBy

-(id) initWithEnum:(NSString*)itemName value:(int) itemValue
{
    if(self = [super init])
    {
        self->name=itemName;
        self->value=itemValue;
    }
    return self;
}

-(NSString*) stringValue
{
    return name;
}
    
-(NSString*) description
{
    return name;
}

-(int) getValue
{
    return value;
}

-(BOOL) isEqualTo:(KPUTicketUpdatedBy *)item
{
    return [name isEqualToString:item->name];
}
   
-(void) serialize:(DDXMLNode*)parent
{
    [parent setStringValue:name];
}
     
+(KPUTicketUpdatedBy*) All
{
    static KPUTicketUpdatedBy* obj=nil;
    if(!obj)
    {
        obj=[[KPUTicketUpdatedBy alloc] initWithEnum: @"All" value: 0];
    }
    return obj;
} 
+(KPUTicketUpdatedBy*) Users
{
    static KPUTicketUpdatedBy* obj=nil;
    if(!obj)
    {
        obj=[[KPUTicketUpdatedBy alloc] initWithEnum: @"Users" value: 1];
    }
    return obj;
} 
+(KPUTicketUpdatedBy*) System
{
    static KPUTicketUpdatedBy* obj=nil;
    if(!obj)
    {
        obj=[[KPUTicketUpdatedBy alloc] initWithEnum: @"System" value: 2];
    }
    return obj;
} 
+(KPUTicketUpdatedBy*) TicketService
{
    static KPUTicketUpdatedBy* obj=nil;
    if(!obj)
    {
        obj=[[KPUTicketUpdatedBy alloc] initWithEnum: @"TicketService" value: 3];
    }
    return obj;
} 
+(KPUTicketUpdatedBy*) Others
{
    static KPUTicketUpdatedBy* obj=nil;
    if(!obj)
    {
        obj=[[KPUTicketUpdatedBy alloc] initWithEnum: @"Others" value: 4];
    }
    return obj;
} 
    
+ (KPUTicketUpdatedBy *)createWithXml:(DDXMLNode *)node
{
    return [KPUTicketUpdatedBy createWithString:[node stringValue]];
}
    
+ (KPUTicketUpdatedBy *)createWithString:(NSString *)value
{
    if([value isEqualToString:@"Users"])
    {
        return [KPUTicketUpdatedBy Users];
    }
    if([value isEqualToString:@"System"])
    {
        return [KPUTicketUpdatedBy System];
    }
    if([value isEqualToString:@"TicketService"])
    {
        return [KPUTicketUpdatedBy TicketService];
    }
    if([value isEqualToString:@"Others"])
    {
        return [KPUTicketUpdatedBy Others];
    }
    return [KPUTicketUpdatedBy All];   
}
    

@end
