//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXMLElement.h"


@interface KPUTicketUpdatedBy : NSObject
{
    int value;
    NSString* name;
}

+(KPUTicketUpdatedBy*) createWithXml:(DDXMLNode*)node;
+(KPUTicketUpdatedBy *)createWithString:(NSString *)value;
-(NSString*) stringValue;
-(NSString*) description;
-(int)getValue;
-(BOOL)isEqualTo:(KPUTicketUpdatedBy *)item;
-(void) serialize:(DDXMLNode*)parent;
        
+(KPUTicketUpdatedBy *) All;    
+(KPUTicketUpdatedBy *) Users;    
+(KPUTicketUpdatedBy *) System;    
+(KPUTicketUpdatedBy *) TicketService;    
+(KPUTicketUpdatedBy *) Others;    
@end