//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUTicketProblemTypeInfo.h"


@implementation KPUTicketProblemTypeInfo
@synthesize PKTicketProblemTypeId;
@synthesize TicketProblemTypeName;
@synthesize IsDefault;
@synthesize FKTicketProblemTypeId;
@synthesize AssetRequired;
@synthesize IsActive;
@synthesize IsStandardWorkRequest;
@synthesize DepartmentIds;
@synthesize FKAssetCategoryId;
@synthesize locationdependant;
@synthesize fKdepartmentid;
@synthesize fKserviceid;

+ (KPUTicketProblemTypeInfo *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.PKTicketProblemTypeId =[NSNumber numberWithInt:0];
        self.FKTicketProblemTypeId =0;
        self.AssetRequired =0;
        self.FKAssetCategoryId =[NSNumber numberWithInt:0];
        self.fKdepartmentid =0;
        self.fKserviceid =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"PKTicketProblemTypeId" index:0])
        {
            self.PKTicketProblemTypeId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"PKTicketProblemTypeId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"TicketProblemTypeName" index:0])
        {
            self.TicketProblemTypeName = [[KPUHelper getNode:__node name:@"TicketProblemTypeName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsDefault" index:0])
        {
            self.IsDefault = [[[KPUHelper getNode:__node name:@"IsDefault" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"FKTicketProblemTypeId" index:0])
        {
            self.FKTicketProblemTypeId = [[[KPUHelper getNode:__node name:@"FKTicketProblemTypeId" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"AssetRequired" index:0])
        {
            self.AssetRequired = [[[KPUHelper getNode:__node name:@"AssetRequired" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"IsActive" index:0])
        {
            self.IsActive = [[[KPUHelper getNode:__node name:@"IsActive" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"IsStandardWorkRequest" index:0])
        {
            self.IsStandardWorkRequest = [[[KPUHelper getNode:__node name:@"IsStandardWorkRequest" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"DepartmentIds" index:0])
        {
            self.DepartmentIds = [[KPUHelper getNode:__node name:@"DepartmentIds" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"FKAssetCategoryId" index:0])
        {
            self.FKAssetCategoryId = [KPUHelper getNumber:[[KPUHelper getNode:__node name:@"FKAssetCategoryId" index:0] stringValue]];
        }
        if([KPUHelper hasValue:__node name:@"locationdependant" index:0])
        {
            self.locationdependant = [[[KPUHelper getNode:__node name:@"locationdependant" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"fKdepartmentid" index:0])
        {
            self.fKdepartmentid = [[[KPUHelper getNode:__node name:@"fKdepartmentid" index:0] stringValue] intValue];
        }
        if([KPUHelper hasValue:__node name:@"fKserviceid" index:0])
        {
            self.fKserviceid = [[[KPUHelper getNode:__node name:@"fKserviceid" index:0] stringValue] intValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __PKTicketProblemTypeIdItemElement=[__request writeElement:PKTicketProblemTypeId type:[NSNumber class] name:@"PKTicketProblemTypeId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__PKTicketProblemTypeIdItemElement!=nil)
    {
        [__PKTicketProblemTypeIdItemElement setStringValue:[self.PKTicketProblemTypeId stringValue]];
    }
             
    DDXMLElement* __TicketProblemTypeNameItemElement=[__request writeElement:TicketProblemTypeName type:[NSString class] name:@"TicketProblemTypeName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__TicketProblemTypeNameItemElement!=nil)
    {
        [__TicketProblemTypeNameItemElement setStringValue:self.TicketProblemTypeName];
    }
             
    DDXMLElement* __IsDefaultItemElement=[__request writeElement:@"IsDefault" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsDefaultItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsDefault]];
             
    DDXMLElement* __FKTicketProblemTypeIdItemElement=[__request writeElement:@"FKTicketProblemTypeId" URI:@"http://www.apoyar.net/" parent:__parent];
    [__FKTicketProblemTypeIdItemElement setStringValue: [NSString stringWithFormat:@"%i", self.FKTicketProblemTypeId]];
             
    DDXMLElement* __AssetRequiredItemElement=[__request writeElement:@"AssetRequired" URI:@"http://www.apoyar.net/" parent:__parent];
    [__AssetRequiredItemElement setStringValue: [NSString stringWithFormat:@"%i", self.AssetRequired]];
             
    DDXMLElement* __IsActiveItemElement=[__request writeElement:@"IsActive" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsActiveItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsActive]];
             
    DDXMLElement* __IsStandardWorkRequestItemElement=[__request writeElement:@"IsStandardWorkRequest" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsStandardWorkRequestItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsStandardWorkRequest]];
             
    DDXMLElement* __DepartmentIdsItemElement=[__request writeElement:DepartmentIds type:[NSString class] name:@"DepartmentIds" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__DepartmentIdsItemElement!=nil)
    {
        [__DepartmentIdsItemElement setStringValue:self.DepartmentIds];
    }
             
    DDXMLElement* __FKAssetCategoryIdItemElement=[__request writeElement:FKAssetCategoryId type:[NSNumber class] name:@"FKAssetCategoryId" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:NO];
    if(__FKAssetCategoryIdItemElement!=nil)
    {
        [__FKAssetCategoryIdItemElement setStringValue:[self.FKAssetCategoryId stringValue]];
    }
             
    DDXMLElement* __locationdependantItemElement=[__request writeElement:@"locationdependant" URI:@"http://www.apoyar.net/" parent:__parent];
    [__locationdependantItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.locationdependant]];
             
    DDXMLElement* __fKdepartmentidItemElement=[__request writeElement:@"fKdepartmentid" URI:@"http://www.apoyar.net/" parent:__parent];
    [__fKdepartmentidItemElement setStringValue: [NSString stringWithFormat:@"%i", self.fKdepartmentid]];
             
    DDXMLElement* __fKserviceidItemElement=[__request writeElement:@"fKserviceid" URI:@"http://www.apoyar.net/" parent:__parent];
    [__fKserviceidItemElement setStringValue: [NSString stringWithFormat:@"%i", self.fKserviceid]];


}
@end
