//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class KPUHelper;
#import "KPURequestResultHandler.h"
#import "DDXML.h"



@interface KPUTicketStatusInfo : NSObject <KPUISerializableObject>


@property (retain,nonatomic,getter=getPKTicketStatusId) NSNumber* PKTicketStatusId;

@property (retain,nonatomic,getter=getTicketStatusName) NSString* TicketStatusName;

@property (retain,nonatomic,getter=getTicketStatusKey) NSString* TicketStatusKey;

@property (retain,nonatomic,getter=getTableColor) NSString* TableColor;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
+(KPUTicketStatusInfo*) createWithXml:(DDXMLElement*)__node __request:(KPURequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request;
@end