//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUTicketInfo_TicketAttributes.h"


@implementation KPUTicketInfo_TicketAttributes

+ (KPUTicketInfo_TicketAttributes *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{



}
@end
