//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.5.2
//
// Created by Quasar Development at 23-03-2015
//
//---------------------------------------------------


#import "KPUHelper.h"
#import "KPUWebsiteAuthHeader.h"


@implementation KPUWebsiteAuthHeader
@synthesize UserName;
@synthesize Password;
@synthesize IsLoggedIn;
@synthesize Url;
@synthesize LanguageCulture;

+ (KPUWebsiteAuthHeader *)createWithXml:(DDXMLElement *)__node __request:(KPURequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KPURequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KPUHelper hasValue:__node name:@"UserName" index:0])
        {
            self.UserName = [[KPUHelper getNode:__node name:@"UserName" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"Password" index:0])
        {
            self.Password = [[KPUHelper getNode:__node name:@"Password" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"IsLoggedIn" index:0])
        {
            self.IsLoggedIn = [[[KPUHelper getNode:__node name:@"IsLoggedIn" index:0] stringValue] boolValue];
        }
        if([KPUHelper hasValue:__node name:@"Url" index:0])
        {
            self.Url = [[KPUHelper getNode:__node name:@"Url" index:0] stringValue];
        }
        if([KPUHelper hasValue:__node name:@"LanguageCulture" index:0])
        {
            self.LanguageCulture = [[KPUHelper getNode:__node name:@"LanguageCulture" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KPURequestResultHandler*) __request
{

             
    DDXMLElement* __UserNameItemElement=[__request writeElement:UserName type:[NSString class] name:@"UserName" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UserNameItemElement!=nil)
    {
        [__UserNameItemElement setStringValue:self.UserName];
    }
             
    DDXMLElement* __PasswordItemElement=[__request writeElement:Password type:[NSString class] name:@"Password" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__PasswordItemElement!=nil)
    {
        [__PasswordItemElement setStringValue:self.Password];
    }
             
    DDXMLElement* __IsLoggedInItemElement=[__request writeElement:@"IsLoggedIn" URI:@"http://www.apoyar.net/" parent:__parent];
    [__IsLoggedInItemElement setStringValue:[KPUHelper toBoolStringFromBool:self.IsLoggedIn]];
             
    DDXMLElement* __UrlItemElement=[__request writeElement:Url type:[NSString class] name:@"Url" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__UrlItemElement!=nil)
    {
        [__UrlItemElement setStringValue:self.Url];
    }
             
    DDXMLElement* __LanguageCultureItemElement=[__request writeElement:LanguageCulture type:[NSString class] name:@"LanguageCulture" URI:@"http://www.apoyar.net/" parent:__parent skipNullProperty:YES];
    if(__LanguageCultureItemElement!=nil)
    {
        [__LanguageCultureItemElement setStringValue:self.LanguageCulture];
    }


}
@end
